import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateEnterpriseClaimV2} from '../src/pipeline/enterprise-claim-gate-v2.js';

const projectId='00000000-0000-4000-8000-000000000001';
const claim={requirement_id:'REQ-030',basis_evidence_ids:['EVD-1']};
const binding=(extra={})=>({project_id:projectId,requirement_id:'REQ-030',mapping_id:'MAP-1',mapping_status:'approved',support_level:'partial_support',evidence_id:'EVD-1',approval_status:'approved',validity_status:'active',source_lineage_verified:true,usable_for_claims:true,material_type:'project_case',evidence_scope:['award_fact'],...extra});
const run=(extra={})=>evaluateEnterpriseClaimV2({projectId,claim,binding:binding(extra)});
const boundary=(claimText,extra={},claimExtra={})=>evaluateEnterpriseClaimV2({projectId,claim:{...claim,...claimExtra,text:claimText},binding:binding(extra)});

test('full/partial support 只投影支撑充分度，未知语义维度保持 unknown',()=>{const full=run({support_level:'full_support'});assert.equal(full.decision,'needs_review');assert.equal(full.dimensions.support_sufficiency,'sufficient');assert.equal(full.dimensions.scope_match,'unknown');assert.equal(full.dimensions.status_match,'unknown');assert.equal(full.dimensions.entity_match,'unknown');assert.equal(run().dimensions.support_sufficiency,'partial');});
test('reference_only 被限制且不得进入 Writer',()=>{const result=run({support_level:'reference_only',usable_for_claims:true});assert.equal(result.decision,'restrict');assert.equal(result.dimensions.support_sufficiency,'insufficient');assert.equal(result.writer_eligible,false);assert.ok(result.reason_codes.includes('REFERENCE_ONLY'));});
test('historical_bid 即使 lineage 完整也不可用',()=>{const result=run({material_type:'historical_bid',usable_for_claims:false});assert.equal(result.decision,'reject');assert.ok(result.reason_codes.includes('SOURCE_NOT_USABLE'));});
test('没有 Mapping、proposed/rejected Mapping 与跨项目 Mapping 均拒绝',()=>{for(const value of [null,binding({mapping_status:'proposed'}),binding({mapping_status:'rejected'}),binding({project_id:'00000000-0000-4000-8000-000000000002'})]){const result=evaluateEnterpriseClaimV2({projectId,claim,binding:value});assert.equal(result.decision,'reject');assert.ok(result.reason_codes.includes('MAPPING_NOT_APPROVED'));}});
test('draft Evidence 与缺失 lineage 分别被拒绝',()=>{assert.ok(run({approval_status:'draft'}).reason_codes.includes('EVIDENCE_NOT_APPROVED'));assert.ok(run({source_lineage_verified:false}).reason_codes.includes('SOURCE_LINEAGE_REQUIRED'));});
test('expired/revoked Evidence 被拒绝，未知 validity 保守复核',()=>{for(const validity_status of ['expired','revoked'])assert.ok(run({validity_status}).reason_codes.includes('EVIDENCE_EXPIRED'));const unknown=run({validity_status:'unknown'});assert.equal(unknown.decision,'needs_review');assert.equal(unknown.dimensions.validity_match,'unknown');assert.equal(unknown.writer_eligible,false);});
test('不可用来源与缺失 support level 均拒绝',()=>{assert.ok(run({usable_for_claims:false}).reason_codes.includes('SOURCE_NOT_USABLE'));assert.ok(run({support_level:null}).reason_codes.includes('SUPPORT_INSUFFICIENT'));});
test('award 事实不得升级为 completed 或 accepted',()=>{for(const value of ['我司已成功完成该项目建设。','我司已完成建设并通过验收。']){const result=boundary(value,{evidence_scope:['award_fact']});assert.equal(result.decision,'reject');assert.equal(result.dimensions.status_match,'mismatch');assert.ok(result.reason_codes.includes('STATUS_OVERCLAIM'));assert.ok(result.reason_codes.includes('EVIDENCE_SCOPE_EXCEEDED'));}});
test('award 安全事实不触发状态升级',()=>{const result=boundary('存在经审核的相关项目中标事实。',{evidence_scope:['award_fact']});assert.notEqual(result.decision,'reject');assert.equal(result.dimensions.status_match,'match');assert.ok(!result.reason_codes.includes('STATUS_OVERCLAIM'));});
test('Enterprise Claim 数量必须由 Evidence 精确支撑',()=>{const unsupported=boundary('我司现有系统接口响应时间不超过1秒。',{content:'具备一般接口集成能力。',source_text:'具备一般接口集成能力。',support_level:'full_support'});assert.equal(unsupported.decision,'reject');assert.equal(unsupported.dimensions.quantitative_match,'mismatch');assert.ok(unsupported.reason_codes.includes('QUANTITATIVE_UNSUPPORTED'));const supported=boundary('现有系统接口响应时间为1秒。',{content:'测试记录显示接口响应时间为1秒。'});assert.equal(supported.dimensions.quantitative_match,'match');});
test('结构化实体与范围 exact match 保留，明确不同实体拒绝',()=>{const exact=boundary('Model A 产品已有登记事实。',{metadata:{product_model:'Model A'},evidence_scope:['registration_fact']},{metadata:{product_model:'Model A',scope:'registration_fact'}});assert.equal(exact.dimensions.entity_match,'match');assert.equal(exact.dimensions.scope_match,'match');const mismatch=boundary('Model B 产品已有登记事实。',{metadata:{product_model:'Model A'},evidence_scope:['registration_fact']},{metadata:{product_model:'Model B',scope:'registration_fact'}});assert.equal(mismatch.decision,'reject');assert.equal(mismatch.dimensions.entity_match,'mismatch');assert.ok(mismatch.reason_codes.includes('ENTITY_MISMATCH'));});
test('明确范围不一致或全范围扩张拒绝，缺少结构化范围时保持 unknown',()=>{const explicit=boundary('相关事实。',{evidence_scope:['award_fact']},{metadata:{scope:'completion_fact'}});assert.equal(explicit.decision,'reject');assert.equal(explicit.dimensions.scope_match,'mismatch');const broad=boundary('全部产品均已取得登记。',{metadata:{product_model:'Model A'},evidence_scope:['registration_fact']});assert.equal(broad.decision,'reject');assert.equal(broad.dimensions.scope_match,'mismatch');assert.ok(broad.reason_codes.includes('EVIDENCE_SCOPE_EXCEEDED'));const unknown=boundary('具备相关产品能力。',{metadata:{},evidence_scope:[]});assert.equal(unknown.decision,'needs_review');assert.equal(unknown.dimensions.scope_match,'unknown');});
test('partial support + unknown scope 保守复核，reference/historical 优先级不放宽',()=>{assert.equal(boundary('具备相关能力。').decision,'needs_review');assert.equal(boundary('具备相关能力。',{support_level:'reference_only'}).decision,'restrict');assert.equal(boundary('具备相关能力。',{material_type:'historical_bid',usable_for_claims:false}).decision,'reject');});
test('通用注册事实 fixture：单一型号匹配，全系列扩张拒绝且 reason domain-neutral',()=>{const evidence={support_level:'full_support',metadata:{subject:'Company A',product_model:'Model A'},evidence_scope:['registration_fact'],validity_status:'active'};const exact=boundary('Model A 产品具有有效医疗器械注册证。',evidence,{metadata:{product_model:'Model A',scope:'registration_fact'}});assert.equal(exact.dimensions.entity_match,'match');assert.equal(exact.dimensions.scope_match,'match');assert.equal(exact.dimensions.validity_match,'match');const broad=boundary('我司全系列医疗器械产品均具有有效注册证。',evidence);assert.equal(broad.decision,'reject');assert.ok(broad.reason_codes.includes('EVIDENCE_SCOPE_EXCEEDED'));assert.ok(broad.reason_codes.every((code)=>!code.startsWith('MEDICAL_')));});
