import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chunkEnterpriseMaterial } from '../src/pipeline/enterprise-material-chunker.js';
import { EvidenceSourceContextResolver } from '../src/pipeline/evidence-source-context-resolver.js';
import { EvidenceService } from '../src/evidence-service.js';

const PROJECT='11111111-1111-4111-8111-111111111111';
const MATERIAL='22222222-2222-4222-8222-222222222222';
const resolver=new EvidenceSourceContextResolver();
const fixture=(source,options={})=>{const material={id:MATERIAL,project_id:PROJECT,material_type:'project_case',extraction_status:'succeeded',extracted_text:source};const chunks=chunkEnterpriseMaterial(MATERIAL,source,options);return{material,chunks};};

test('anchor_only 生成可回溯连续 span 并由后端 hash',()=>{const{material,chunks}=fixture('甲段。\n\n乙段。');const span=resolver.resolve({material,chunks,anchorChunkId:chunks[1].chunk_id,strategy:'anchor_only'});assert.equal(span.source_text,'乙段。');assert.equal(span.source_hash,createHash('sha256').update(span.source_text).digest('hex'));assert.equal(span.source_location.anchor_chunk_id,chunks[1].chunk_id);assert.equal(span.source_location.resolver_version,'evidence-source-span-v1');});

test('长 paragraph 的多 Chunk 重建为完整原段落且不跨段',()=>{const paragraph='甲'.repeat(50);const source=`${paragraph}\n\n下一段`;const{material,chunks}=fixture(source,{maxChars:12});const span=resolver.resolve({material,chunks,anchorChunkId:chunks[2].chunk_id,strategy:'paragraph_reconstruction'});assert.equal(span.source_text,paragraph);assert.equal(span.source_location.paragraph_start,1);assert.equal(span.source_location.paragraph_end,1);});

test('heading_group 包含真实标题及同组正文并在下一同级标题停止',()=>{const source='# 系统集成\n\n支持接口集成。\n\n支持系统对接。\n\n# 资质\n\nISO9001';const{material,chunks}=fixture(source);const span=resolver.resolve({material,chunks,anchorChunkId:chunks[1].chunk_id,strategy:'heading_group'});assert.match(span.source_text,/^# 系统集成/);assert.match(span.source_text,/支持系统对接/);assert.doesNotMatch(span.source_text,/资质/);});

test('Anchor 本身为 heading 时 auto 读取其下受限正文',()=>{const source='# 资质认证\n\nISO9001\n\nISO27001';const{material,chunks}=fixture(source);const span=resolver.resolve({material,chunks,anchorChunkId:chunks[0].chunk_id});assert.equal(span.source_location.resolution_method,'heading_group');assert.match(span.source_text,/ISO9001/);assert.match(span.source_text,/ISO27001/);});

test('bounded fallback 保持连续、包含 Anchor 且不跨明确 heading',()=>{const source='甲\n\n乙\n\n丙\n\n# 新章\n\n丁';const{material,chunks}=fixture(source);const span=resolver.resolve({material,chunks,anchorChunkId:chunks[1].chunk_id,strategy:'bounded_paragraph_window'});assert.match(span.source_text,/甲[\s\S]*乙[\s\S]*丙/);assert.doesNotMatch(span.source_text,/新章/);});

test('跨 Material、跨 chunker version 和不包含 Anchor 均被阻断',()=>{const{material,chunks}=fixture('甲\n\n乙');assert.throws(()=>resolver.resolve({material,chunks:[{...chunks[0],material_id:'other'}],anchorChunkId:chunks[0].chunk_id}),/Retrieval Anchor/);const mixed=[chunks[0],{...chunks[1],chunker_version:'future'}];const span=resolver.resolve({material,chunks:mixed,anchorChunkId:chunks[0].chunk_id,strategy:'bounded_paragraph_window'});assert.equal(span.source_text,'甲');});

test('客户端不得伪造 span、source text、hash 或 range',async()=>{const{material,chunks}=fixture('可验证原文');const repository={getCompanyMaterial:async()=>material,getMaterialChunk:async()=>chunks[0],findInvalidConfirmedRequirementIds:async()=>[],createEvidenceRecord:async(value)=>value};const service=new EvidenceService({repository});await assert.rejects(()=>service.create(PROJECT,{material_id:MATERIAL,source_chunk_id:chunks[0].chunk_id,title:'x',content:'x',resolved_source_span:{source_text:'伪造'}}),(error)=>error.code==='EVIDENCE_SOURCE_LINEAGE_FORBIDDEN');await assert.rejects(()=>service.create(PROJECT,{material_id:MATERIAL,source_chunk_id:chunks[0].chunk_id,title:'x',content:'x',source_text:'伪造'}),(error)=>error.code==='EVIDENCE_SOURCE_LINEAGE_INVALID');});

test('同 Anchor 完全相同 Span 去重，不同合法 Span 可创建新 draft 且不继承审批',async()=>{const source='# 标题\n\n原文能力。';const{material,chunks}=fixture(source);let records=[];const repository={getRetrievalEvidenceSource:async()=>({status:'succeeded',material_id:MATERIAL,chunk_id:chunks[1].chunk_id,material_type:'project_case',original_name:'m',...chunks[1]}),getCompanyMaterial:async()=>material,listMaterialChunks:async()=>chunks,getMaterialChunk:async()=>chunks[1],findInvalidConfirmedRequirementIds:async()=>[],findEvidenceBySourceSpan:async(_p,_m,start,end,hash)=>records.find((item)=>item.start===start&&item.end===end&&item.source_hash===hash)||null,createEvidenceRecord:async(value)=>{const item={id:String(records.length+1),approval_status:'draft',start:value.sourceLocation.char_start,end:value.sourceLocation.char_end,source_hash:value.sourceHash,...value};records.push(item);return item;}};const service=new EvidenceService({repository});const full=await service.createFromRetrieval(PROJECT,'REQ-030',{retrieval_run_id:PROJECT,chunk_id:chunks[1].chunk_id});assert.equal(full.created,true);assert.equal(full.evidence.approval_status,'draft');assert.equal((await service.createFromRetrieval(PROJECT,'REQ-030',{retrieval_run_id:PROJECT,chunk_id:chunks[1].chunk_id})).created,false);const anchor=await service.createFromRetrieval(PROJECT,'REQ-030',{retrieval_run_id:PROJECT,chunk_id:chunks[1].chunk_id,resolution_strategy:'anchor_only'});assert.equal(anchor.created,true);assert.equal(records.length,2);assert.equal(anchor.evidence.approval_status,'draft');});
