import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { createEvidenceReviewContract, EVIDENCE_REVIEW_CONTRACT_VERSION, REVIEW_DIMENSIONS } from '../src/pipeline/evidence-review-contract.js';
import { EvidenceReviewService } from '../src/evidence-review-service.js';

const sha=(value)=>createHash('sha256').update(value).digest('hex');
const context=(overrides={})=>({project_id:'11111111-1111-4111-8111-111111111111',requirement_db_id:'22222222-2222-4222-8222-222222222222',requirement_id:'REQ-001',requirement_text:'接口响应时间应不超过1秒。',retrieval_run_id:'33333333-3333-4333-8333-333333333333',retrieval_candidate_id:'MCH-1',source_span_id:'ESPAN-1',source_text:'测试结果平均1.4秒。',source_text_hash:sha('测试结果平均1.4秒。'),content_role:'performance_test',material_type:'technical_whitepaper',...overrides});
const dimensions=(overrides={})=>Object.fromEntries(REVIEW_DIMENSIONS.map((name)=>[name,overrides[name]||'unknown']));
const assessment=(overrides={})=>({semantic_relevance:'relevant',evidence_capability:'capable',support_level:'partial_support',review_dimensions:dimensions(),requires_human_review:true,...overrides});

test('Relevant quantitative conflict 保留为 capable 负向证据且禁止自动 full support',()=>{const review=createEvidenceReviewContract(context(),assessment({support_level:'full_support',review_dimensions:dimensions({quantitative_match:'mismatch'})}));assert.equal(review.semantic_relevance,'relevant');assert.equal(review.evidence_capability,'capable');assert.equal(review.support_level,'conflict');assert.equal(review.review_dimensions.quantitative_match,'mismatch');assert.ok(review.reason_codes.includes('QUANTITATIVE_MISMATCH'));assert.equal(review.review_status,'needs_review');});

test('Relevant but marketing not evidence capable，不能因语义相关获得 support',()=>{const review=createEvidenceReviewContract(context({content_role:'marketing_claim'}),assessment({support_level:'full_support',review_dimensions:dimensions({subject_match:'match'})}));assert.equal(review.semantic_relevance,'relevant');assert.equal(review.evidence_capability,'not_capable');assert.equal(review.support_level,'insufficient');assert.ok(review.reason_codes.includes('SOURCE_NOT_EVIDENCE_CAPABLE'));});

test('Qualification 缺少有效期保持 unknown，不默认有效',()=>{const review=createEvidenceReviewContract(context({requirement_text:'供应商应具备ISO 27001认证。',source_text:'ISO 27001认证证书',source_text_hash:sha('ISO 27001认证证书'),content_role:'qualification',material_type:'qualification'}),assessment({review_dimensions:dimensions({subject_match:'match',entity_match:'match',validity_match:'unknown'})}));assert.equal(review.review_dimensions.validity_match,'unknown');assert.ok(review.reason_codes.includes('VALIDITY_UNKNOWN'));assert.equal(review.requires_human_review,true);});

test('Compatibility 仅覆盖部分产品保持 partial_support',()=>{const review=createEvidenceReviewContract(context({requirement_text:'兼容国产操作系统及数据库。',content_role:'compatibility_evidence'}),assessment({support_level:'partial_support',review_dimensions:dimensions({subject_match:'match',scope_match:'unknown'})}));assert.equal(review.support_level,'partial_support');assert.ok(review.reason_codes.includes('SUPPORT_PARTIAL'));});

test('Project case 未明确 lifecycle 状态时 status unknown，不推断完成或验收',()=>{const review=createEvidenceReviewContract(context({requirement_text:'具备类似项目经验。',content_role:'project_case',material_type:'project_case'}),assessment({review_dimensions:dimensions({subject_match:'match',status_match:'unknown'})}));assert.equal(review.review_dimensions.status_match,'unknown');assert.ok(review.reason_codes.includes('STATUS_UNKNOWN'));assert.notEqual(review.review_status,'approved');});

test('Historical bid 永远 reference_only',()=>{const review=createEvidenceReviewContract(context({material_type:'historical_bid'}),assessment({evidence_capability:'capable',support_level:'full_support',review_dimensions:dimensions({subject_match:'match'})}));assert.equal(review.evidence_capability,'reference_only');assert.equal(review.support_level,'reference_only');assert.ok(review.reason_codes.includes('REFERENCE_ONLY_SOURCE'));});

test('Irrelevant Candidate 与 unknown 均不被伪装为 match',()=>{const review=createEvidenceReviewContract(context(),assessment({semantic_relevance:'irrelevant',review_dimensions:dimensions()}));assert.equal(review.evidence_capability,'not_capable');assert.equal(review.support_level,'insufficient');assert.ok(Object.values(review.review_dimensions).every((value)=>value==='unknown'));});

test('Machine reviewer 无论输入何种状态都只能 proposed 或 needs_review',()=>{const review=createEvidenceReviewContract(context(),assessment({review_status:'approved',requires_human_review:false,review_dimensions:dimensions({subject_match:'match',scope_match:'match',status_match:'match',quantitative_match:'match',entity_match:'match',validity_match:'match',source_authority:'match',support_sufficiency:'match'}),support_level:'full_support'}));assert.equal(review.review_status,'proposed');assert.equal(review.reviewer_type,'machine');});

test('相同输入 identity 稳定，Requirement/Span/Contract/Reviewer 变化均产生新版本',()=>{const base=createEvidenceReviewContract(context(),assessment(),{reviewerVersion:'r1'});assert.equal(createEvidenceReviewContract(context(),assessment(),{reviewerVersion:'r1'}).review_id,base.review_id);assert.notEqual(createEvidenceReviewContract(context({requirement_text:'已修改 Requirement'}),assessment(),{reviewerVersion:'r1'}).review_id,base.review_id);assert.notEqual(createEvidenceReviewContract(context({source_span_id:'ESPAN-2',source_text_hash:sha('另一 Span')}),assessment(),{reviewerVersion:'r1'}).review_id,base.review_id);assert.notEqual(createEvidenceReviewContract(context(),assessment(),{reviewerVersion:'r1',contractVersion:'evidence-review-v2'}).review_id,base.review_id);assert.notEqual(createEvidenceReviewContract(context(),assessment(),{reviewerVersion:'r2'}).review_id,base.review_id);});

test('人工 approve/reject 为独立动作并记录 reviewer/version',async()=>{for(const decision of ['approve','reject']){let decided;const current={review_id:'EREVIEW-X',review_status:'needs_review',contract_version:EVIDENCE_REVIEW_CONTRACT_VERSION,requirement_text:'原文',requirement_text_hash:sha('原文'),source_text_hash:sha('来源'),current_source_text_hash:sha('来源')};const service=new EvidenceReviewService({repository:{getEvidenceCandidateReviewCurrent:async()=>current,decideEvidenceCandidateReview:async(value)=>{decided=value;return{...current,review_status:value.status,reviewed_by:value.reviewer,human_review_version:1};},invalidateEvidenceCandidateReview:async()=>{} }});const result=await service.decide('EREVIEW-X',decision,{reviewer:'human-reviewer',note:'人工核验'});assert.equal(result.review_status,decision==='approve'?'approved':'rejected');assert.equal(result.reviewed_by,'human-reviewer');assert.equal(result.human_review_version,1);assert.equal(decided.note,'人工核验');}});

test('Requirement、Source Span 或 Contract 变化使旧审批失效',async()=>{for(const mutation of [{requirement_text:'变化后'},{current_source_text_hash:sha('变化后')},{contract_version:'evidence-review-v0'}]){let invalidated=false;const current={review_status:'needs_review',contract_version:EVIDENCE_REVIEW_CONTRACT_VERSION,requirement_text:'原文',requirement_text_hash:sha('原文'),source_text_hash:sha('来源'),current_source_text_hash:sha('来源'),...mutation};const service=new EvidenceReviewService({repository:{getEvidenceCandidateReviewCurrent:async()=>current,invalidateEvidenceCandidateReview:async()=>{invalidated=true;},decideEvidenceCandidateReview:async()=>assert.fail('不得继承旧批准')}});await assert.rejects(()=>service.decide('EREVIEW-X','approve',{reviewer:'human'}),(error)=>error.code==='EVIDENCE_REVIEW_VERSION_INVALIDATED');assert.equal(invalidated,true);}});

test('Review Service 只创建 Review，不创建 Fact/Mapping/Claim 或调用 Writer',async()=>{const calls={review:0,fact:0,mapping:0,claim:0,writer:0};const repository={getEvidenceReviewCandidate:async()=>context(),upsertEvidenceCandidateReview:async(value)=>{calls.review+=1;return value;}};const semanticReviewer={review:async()=>assessment()};const service=new EvidenceReviewService({repository,semanticReviewer});const review=await service.propose({projectId:context().project_id,requirementId:'REQ-001',retrievalRunId:context().retrieval_run_id,retrievalCandidateId:'MCH-1',sourceSpanId:'ESPAN-1'});assert.equal(review.review_status,'needs_review');assert.deepEqual(calls,{review:1,fact:0,mapping:0,claim:0,writer:0});});
