import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateEnterpriseClaimV2,applyEnterpriseEvaluationToLegacyDecision} from '../src/pipeline/enterprise-claim-gate-v2.js';

const projectId='00000000-0000-4000-8000-000000000001';
const evidenceId='EVD-1';
const claim=(text,extra={})=>({requirement_id:'REQ-030',basis_evidence_ids:[evidenceId],text,...extra});
const fact=(extra={})=>({fact_id:'EFACT-1',project_id:projectId,evidence_id:evidenceId,review_status:'approved',is_current:true,version:1,fact_type:'project_award',subject_json:{type:'organization',name:'Company A',identifier:null},entities_json:[{type:'procurement_item',name:'Platform A',identifier:null,relation:'awarded_item'}],fact_status:'award',fact_scopes_json:['award_fact'],quantities_json:[],validity_json:{status:'not_applicable'},...extra});
const binding=(extra={})=>({project_id:projectId,requirement_id:'REQ-030',mapping_id:'MAP-1',mapping_status:'approved',support_level:'partial_support',evidence_id:evidenceId,approval_status:'approved',validity_status:'active',source_lineage_verified:true,usable_for_claims:true,material_type:'project_case',evidence_scope:['award_fact'],evidence_facts:[fact()],...extra});
const run=(textValue,bindingExtra={},claimExtra={})=>evaluateEnterpriseClaimV2({projectId,claim:claim(textValue,claimExtra),binding:binding(bindingExtra)});

test('REQ-030 award Fact 允许安全表述但拒绝完成和验收升级',()=>{const safe=run('Company A 存在 Platform A 相关项目中标事实。',{}, {metadata:{subject:'Company A',procurement_item:'Platform A',scope:'award_fact'}});assert.notEqual(safe.decision,'reject');assert.equal(safe.dimensions.status_match,'match');assert.equal(safe.dimensions.scope_match,'match');const risky=run('Company A 已成功完成 Platform A 建设并通过验收。',{}, {metadata:{subject:'Company A',procurement_item:'Platform A'}});assert.equal(risky.decision,'reject');assert.equal(risky.dimensions.status_match,'mismatch');assert.equal(risky.dimensions.scope_match,'mismatch');assert.ok(risky.reason_codes.includes('STATUS_OVERCLAIM'));assert.ok(risky.reason_codes.includes('EVIDENCE_SCOPE_EXCEEDED'));assert.equal(risky.writer_eligible,false);});

test('REQ-016 integration Fact 无数量时拒绝 ≤1秒，requirement_response 不进入 Fact Gate',()=>{const integration=fact({fact_id:'EFACT-I',fact_type:'integration_capability',fact_status:'unknown',fact_scopes_json:['integration_capability_reference'],entities_json:[],quantities_json:[]});const result=run('现有系统接口响应时间≤1秒。',{requirement_id:'REQ-016',evidence_scope:['integration_capability_reference'],evidence_facts:[integration]},{requirement_id:'REQ-016'});assert.equal(result.decision,'reject');assert.equal(result.dimensions.quantitative_match,'mismatch');assert.ok(result.reason_codes.includes('QUANTITATIVE_UNSUPPORTED'));const untouched=applyEnterpriseEvaluationToLegacyDecision({claim:{claim_type:'requirement_response'},decision:{decision:'approved'}},result);assert.equal(untouched.v2_evaluation.decision,'reject');});

test('Fact quantity 使用 decimal string 与 operator 精确判断',()=>{const performance=fact({fact_id:'EFACT-P',fact_type:'performance',fact_status:'verified',fact_scopes_json:['performance_fact'],quantities_json:[{metric:'response_latency',operator:'lte',value:'1',unit:'秒',source_text:'响应时间不超过1秒'}],validity_json:{status:'active'}});const source={support_level:'full_support',evidence_scope:['performance_fact'],evidence_facts:[performance]};const exact=run('Company A 的 Platform A 已验证响应时间≤1秒。',source,{metadata:{subject:'Company A',procurement_item:'Platform A',scope:'performance_fact'}});assert.equal(exact.dimensions.quantitative_match,'match');const stronger=run('Company A 的 Platform A 已验证响应时间≤0.5秒。',source,{metadata:{subject:'Company A',procurement_item:'Platform A',scope:'performance_fact'}});assert.equal(stronger.dimensions.quantitative_match,'mismatch');assert.ok(stronger.reason_codes.includes('QUANTITATIVE_UNSUPPORTED'));});

test('REQ-187 reference_only 保持 restrict，Fact 不升级 Mapping support_level',()=>{const qualification=fact({fact_id:'EFACT-Q',fact_type:'qualification',fact_status:'unknown',fact_scopes_json:['qualification_fact'],entities_json:[],validity_json:{status:'active'}});const result=run('存在相关资质事实。',{requirement_id:'REQ-187',support_level:'reference_only',evidence_scope:['qualification_fact'],evidence_facts:[qualification]},{requirement_id:'REQ-187',metadata:{scope:'qualification_fact'}});assert.equal(result.dimensions.support_sufficiency,'insufficient');assert.equal(result.dimensions.source_authority,'reference_only');assert.equal(result.decision,'restrict');assert.equal(result.writer_eligible,false);});

test('domain-neutral full_support 精确事实可 allow，全系列扩张 reject',()=>{const registration=fact({fact_id:'EFACT-R',fact_type:'registration',subject_json:{type:'organization',name:'Company A'},entities_json:[{type:'product_model',name:'Model A',relation:'registered_product'},{type:'certificate',identifier:'CERT-001',relation:'registration'}],fact_status:'registered',fact_scopes_json:['registration_fact'],validity_json:{status:'active'}});const source={support_level:'full_support',evidence_scope:['registration_fact'],evidence_facts:[registration]};const exact=run('Company A 的 Model A 产品具有有效注册证 CERT-001。',source,{metadata:{subject:'Company A',product_model:'Model A',certificate:'CERT-001',scope:'registration_fact'}});assert.equal(exact.decision,'allow');assert.equal(exact.writer_eligible,true);for(const key of ['subject_match','entity_match','status_match','scope_match','validity_match'])assert.equal(exact.dimensions[key],'match');assert.equal(exact.dimensions.quantitative_match,'not_applicable');const broad=run('Company A 全系列产品均具有注册证 CERT-001。',source,{metadata:{subject:'Company A',certificate:'CERT-001',scope:'registration_fact'}});assert.equal(broad.decision,'reject');assert.equal(broad.dimensions.entity_match,'mismatch');assert.equal(broad.dimensions.scope_match,'mismatch');});

test('Fact draft、rejected、superseded、跨项目和错误 Evidence 均不进入正式判断',()=>{for(const invalid of [fact({review_status:'draft'}),fact({review_status:'rejected'}),fact({is_current:false}),fact({project_id:'00000000-0000-4000-8000-000000000002'}),fact({evidence_id:'EVD-OTHER'})]){const result=run('Company A 存在相关项目中标事实。',{evidence_facts:[invalid]});const provenance=result.deterministic_checks.find((item)=>item.check==='evidence_fact_ids_used');assert.equal(provenance.actual.fact_ids.length,0);assert.notEqual(result.decision,'allow');}});

test('Fact 不能绕过 Mapping、reference_only 或 v2 rejected legacy projection',()=>{for(const mapping_status of ['proposed','rejected']){const result=run('Company A 存在相关项目中标事实。',{mapping_status});assert.equal(result.decision,'reject');assert.ok(result.reason_codes.includes('MAPPING_NOT_APPROVED'));}assert.equal(run('Company A 存在相关项目中标事实。',{support_level:'reference_only'}).writer_eligible,false);const rejected=run('Company A 已完成建设。');const projected=applyEnterpriseEvaluationToLegacyDecision({claim:claim('x'),decision:{decision:'approved'}},rejected);assert.equal(projected.decision.decision,'rejected');});

test('明确 subject/entity mismatch、Fact validity 失效均 hard reject',()=>{const subject=run('Company B 存在相关项目中标事实。',{}, {metadata:{subject:'Company B',scope:'award_fact'}});assert.equal(subject.dimensions.subject_match,'mismatch');assert.equal(subject.decision,'reject');const entity=run('Company A 的 Platform B 存在中标事实。',{}, {metadata:{subject:'Company A',procurement_item:'Platform B',scope:'award_fact'}});assert.equal(entity.dimensions.entity_match,'mismatch');assert.equal(entity.decision,'reject');for(const status of ['expired','revoked']){const invalid=run('Company A 存在 Platform A 中标事实。',{evidence_facts:[fact({validity_json:{status}})]},{metadata:{subject:'Company A',procurement_item:'Platform A',scope:'award_fact'}});assert.equal(invalid.dimensions.validity_match,'mismatch');assert.equal(invalid.decision,'reject');}});

test('approved/current Facts 冲突时不静默选择，进入 needs_review 并记录版本 provenance',()=>{const conflict=fact({fact_id:'EFACT-2',version:2,fact_status:'completed'});const result=run('Company A 存在 Platform A 相关事实。',{support_level:'full_support',evidence_facts:[fact(),conflict]},{metadata:{subject:'Company A',procurement_item:'Platform A'}});assert.equal(result.decision,'needs_review');assert.ok(result.reason_codes.includes('HUMAN_REVIEW_REQUIRED'));const provenance=result.deterministic_checks.find((item)=>item.check==='evidence_fact_provenance');assert.deepEqual(provenance.actual.facts,[{fact_id:'EFACT-1',version:1},{fact_id:'EFACT-2',version:2}]);});

test('多 Fact 只组合当前 Claim 明确相关的事实',()=>{const unrelated=fact({fact_id:'EFACT-U',fact_type:'qualification',subject_json:{type:'organization',name:'Company B'},entities_json:[{type:'certificate',identifier:'CERT-X',relation:'qualification'}],fact_status:'certified',fact_scopes_json:['qualification_fact']});const result=run('Company A 存在 Platform A 中标事实。',{evidence_facts:[fact(),unrelated]},{metadata:{subject:'Company A',procurement_item:'Platform A',scope:'award_fact'}});const provenance=result.deterministic_checks.find((item)=>item.check==='evidence_fact_provenance');assert.deepEqual(provenance.actual.facts,[{fact_id:'EFACT-1',version:1}]);});

test('Evidence Fact Gate Core 无行业专属规则',async()=>{const {readFile}=await import('node:fs/promises');for(const file of ['../src/pipeline/evidence-fact-claim-evaluator.js','../src/pipeline/enterprise-claim-gate-v2.js']){const source=await readFile(new URL(file,import.meta.url),'utf8');for(const token of ['smart_city','medical','智慧城市','医疗器械','国产化'])assert.equal(source.includes(token),false);}});
