import test from 'node:test';
import assert from 'node:assert/strict';
import {EvidenceFactService} from '../src/evidence-fact-service.js';

const PROJECT='00000000-0000-4000-8000-000000000001';
const EVIDENCE='00000000-0000-4000-8000-000000000002';
const SOURCE='供应商东软集团股份有限公司中标数据共享交换平台软件项目，合同金额为10000000000000000.01元。';
const baseEvidence={id:EVIDENCE,project_id:PROJECT,approval_status:'approved',evidence_origin:'enterprise',source_lineage_verified:true,source_text:SOURCE,source_hash:'source-hash',source_location:{paragraph_start:1},evidence_scope:['award_fact','contract_amount'],material_type:'project_case'};
const input={fact_type:'project_award',subject:{type:'organization',name:'东软集团股份有限公司'},entities:[{type:'procurement_item',name:'数据共享交换平台软件',relation:'awarded_item'}],fact_status:'award',fact_scopes:['award_fact'],quantities:[],validity:{status:'not_applicable'},created_by:'reviewer'};

function fixture(overrides={}){let stored;const repository={getEvidenceFactSource:async()=>baseEvidence,createEvidenceFact:async(value)=>{stored={id:'00000000-0000-4000-8000-000000000003',fact_id:value.factId,project_id:value.projectId,evidence_id:value.evidenceId,review_status:'draft',version:value.version,...value};return stored;},getEvidenceFactByIdentifier:async()=>stored,listEvidenceFacts:async()=>stored?[stored]:[],listApprovedEvidenceFacts:async()=>[],decideEvidenceFact:async(_id,decision,reviewedBy,reviewNotes)=>stored?.review_status==='draft'?(stored={...stored,review_status:decision,reviewed_by:reviewedBy,review_notes:reviewNotes}):null,...overrides};return{repository,service:new EvidenceFactService({repository}),get stored(){return stored;},set stored(value){stored=value;}};}

test('通用中标事实保持来源、draft 生命周期和可扩展类型',async()=>{const ctx=fixture();const fact=await ctx.service.create(PROJECT,EVIDENCE,{...input,fact_type:'procurement:award',domain_metadata:{namespace:'public_procurement',version:'1',values:{notice_type:'award'}}});assert.match(fact.fact_id,/^EFACT-[A-F0-9-]{36}$/);assert.equal(fact.review_status,'draft');assert.equal(fact.sourceText,SOURCE);assert.deepEqual(fact.sourceLocation,{paragraph_start:1});assert.equal(fact.sourceHash,'source-hash');assert.deepEqual(fact.domainMetadata,{namespace:'public_procurement',version:'1',values:{notice_type:'award'}});});

test('量化事实必须逐字来自原文且十进制区间不经过浮点判断',async()=>{const ctx=fixture();await assert.rejects(()=>ctx.service.create(PROJECT,EVIDENCE,{...input,quantities:[{metric:'response_time',operator:'lte',value:'1',unit:'秒',source_text:'接口能力'}]}),(error)=>error.code==='EVIDENCE_FACT_QUANTITY_SOURCE_INVALID');const rangeSource=`${SOURCE}合同金额区间为10000000000000000.01至10000000000000000.02元。`;const range=fixture({getEvidenceFactSource:async()=>({...baseEvidence,source_text:rangeSource})});const quantitySource='合同金额区间为10000000000000000.01至10000000000000000.02元';const fact=await range.service.create(PROJECT,EVIDENCE,{...input,fact_scopes:['award_fact','contract_amount'],quantities:[{metric:'contract_amount',operator:'range',value:{min:'10000000000000000.01',max:'10000000000000000.02'},unit:'元',source_text:quantitySource}]});assert.equal(fact.quantities[0].value.min,'10000000000000000.01');await assert.rejects(()=>range.service.create(PROJECT,EVIDENCE,{...input,quantities:[{metric:'contract_amount',operator:'range',value:{min:'10000000000000000.02',max:'10000000000000000.01'},unit:'元',source_text:quantitySource}]}),(error)=>error.code==='EVIDENCE_FACT_QUANTITY_VALUE_INVALID');});

test('不得伪造安全检测证书实体、来源或直接批准',async()=>{const ctx=fixture();for(const body of [{...input,entities:[{type:'certificate',name:'信息安全检测报告',relation:'proves'}]},{...input,source_text:'伪造原文'},{...input,source_hash:'fake'},{...input,source_location:{page:99}},{...input,review_status:'approved'}])await assert.rejects(()=>ctx.service.create(PROJECT,EVIDENCE,body),(error)=>['EVIDENCE_FACT_GROUNDING_FAILED','EVIDENCE_FACT_SOURCE_MISMATCH','EVIDENCE_FACT_SOURCE_FORBIDDEN','EVIDENCE_FACT_DIRECT_APPROVAL_FORBIDDEN'].includes(error.code));});

test('REQ-016 与 REQ-187 只保存原文明确的能力和资质边界',async()=>{const integration='企业材料记录系统接口集成能力。';const capability=fixture({getEvidenceFactSource:async()=>({...baseEvidence,source_text:integration,evidence_scope:['integration_capability_reference']})});const caseB=await capability.service.create(PROJECT,EVIDENCE,{fact_type:'capability_reference',subject:{type:'organization'},entities:[{type:'system',name:'系统',relation:'integration_target'}],fact_status:'unknown',fact_scopes:['integration_capability_reference'],quantities:[],validity:{status:'unknown'},created_by:'reviewer'});assert.deepEqual(caseB.quantities,[]);const qualification='企业材料记录相关信息安全资质。';const qualified=fixture({getEvidenceFactSource:async()=>({...baseEvidence,source_text:qualification,evidence_scope:['qualification_fact']})});const caseC=await qualified.service.create(PROJECT,EVIDENCE,{fact_type:'qualification',subject:{type:'organization'},entities:[],fact_status:'unknown',fact_scopes:['qualification_fact'],quantities:[],validity:{status:'unknown'},created_by:'reviewer'});assert.deepEqual(caseC.entities,[]);});

test('Evidence 审批、项目归属和可信 lineage 均为前置门禁',async()=>{for(const [evidence,code] of [[null,'EVIDENCE_NOT_FOUND'],[{...baseEvidence,approval_status:'draft'},'EVIDENCE_NOT_APPROVED'],[{...baseEvidence,source_lineage_verified:false},'EVIDENCE_SOURCE_LINEAGE_REQUIRED']]){const ctx=fixture({getEvidenceFactSource:async()=>evidence});await assert.rejects(()=>ctx.service.create(PROJECT,EVIDENCE,input),(error)=>error.code===code);}});

test('状态、scope、operator 与 validity 都按冻结契约校验',async()=>{const ctx=fixture();await assert.rejects(()=>ctx.service.create(PROJECT,EVIDENCE,{...input,fact_status:'completed'}),(error)=>error.code==='EVIDENCE_FACT_STATUS_UNSUPPORTED');await assert.rejects(()=>ctx.service.create(PROJECT,EVIDENCE,{...input,fact_scopes:['completed_project_experience']}),(error)=>error.code==='EVIDENCE_FACT_SCOPE_UNSUPPORTED');await assert.rejects(()=>ctx.service.create(PROJECT,EVIDENCE,{...input,quantities:[{metric:'amount',operator:'about',value:'1',unit:'元',source_text:'1元'}]}),(error)=>error.code==='EVIDENCE_FACT_QUANTITY_OPERATOR_INVALID');await assert.rejects(()=>ctx.service.create(PROJECT,EVIDENCE,{...input,validity:{status:'active',valid_from:'2027-01-01',valid_until:'2026-01-01'}}),(error)=>error.code==='EVIDENCE_FACT_VALIDITY_INVALID');});

test('医疗风格 fixture 只使用通用 Contract，不需要行业硬编码',async()=>{const source='Company A 的产品型号 Model A 已取得注册证 CERT-001，有效期至2028-12-31。';const ctx=fixture({getEvidenceFactSource:async()=>({...baseEvidence,source_text:source,evidence_scope:['registration_fact']})});const fact=await ctx.service.create(PROJECT,EVIDENCE,{fact_type:'registration',subject:{type:'organization',name:'Company A'},entities:[{type:'product_model',name:'Model A',relation:'registered_product'},{type:'certificate',identifier:'CERT-001',relation:'registration'}],fact_status:'registered',fact_scopes:['registration_fact'],validity:{status:'active',valid_until:'2028-12-31'},domain_metadata:{namespace:'regulated_product',version:'1',values:{class:'unknown'}},created_by:'reviewer'});assert.equal(fact.factStatus,'registered');assert.equal(fact.domainMetadata.namespace,'regulated_product');});

test('审核只能从 draft 执行一次，替代版本只能基于同 Evidence 的 approved Fact',async()=>{const ctx=fixture();const original=await ctx.service.create(PROJECT,EVIDENCE,input);const approved=await ctx.service.decide(original.fact_id,'approved',{reviewed_by:'auditor',review_notes:'原文核验'});assert.equal(approved.review_status,'approved');await assert.rejects(()=>ctx.service.decide(original.fact_id,'rejected',{reviewed_by:'auditor'}),(error)=>error.code==='EVIDENCE_FACT_NOT_FOUND');const replacement=await ctx.service.supersede(original.fact_id,{...input,created_by:'editor'});assert.equal(replacement.version,2);assert.equal(replacement.supersedesId,original.id);const invalid=fixture({getEvidenceFactByIdentifier:async()=>({...approved,project_id:'00000000-0000-4000-8000-000000000099'})});await assert.rejects(()=>invalid.service.create(PROJECT,EVIDENCE,{...input,supersedes_fact_id:original.fact_id}),(error)=>error.code==='EVIDENCE_FACT_SUPERSEDES_INVALID');});

test('Evidence Fact Core 不包含行业专属 Gate 分支',async()=>{const {readFile}=await import('node:fs/promises');const source=await readFile(new URL('../src/evidence-fact-service.js',import.meta.url),'utf8');for(const token of ['smart_city','智慧城市','医疗器械','国产化'])assert.equal(source.includes(token),false);});
