import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chunkEnterpriseMaterial } from '../src/pipeline/enterprise-material-chunker.js';
import { EvidenceSourceContextResolver } from '../src/pipeline/evidence-source-context-resolver.js';
import { EvidenceService } from '../src/evidence-service.js';
import { EvidenceSourceSpanService } from '../src/evidence-source-span-service.js';
import { SOURCE_SPAN_MAX_CHARS } from '../src/pipeline/evidence-source-context-resolver.js';

const PROJECT='11111111-1111-4111-8111-111111111111';
const MATERIAL='22222222-2222-4222-8222-222222222222';
const resolver=new EvidenceSourceContextResolver();
const fixture=(source,options={})=>{const material={id:MATERIAL,project_id:PROJECT,material_type:'project_case',extraction_status:'succeeded',extracted_text:source};const chunks=chunkEnterpriseMaterial(MATERIAL,source,options);return{material,chunks};};

test('anchor_only 生成可回溯连续 span 并由后端 hash',()=>{const{material,chunks}=fixture('甲段。\n\n乙段。');const span=resolver.resolve({material,chunks,anchorChunkId:chunks[1].chunk_id,strategy:'anchor_only'});assert.equal(span.source_text,'乙段。');assert.equal(span.source_hash,createHash('sha256').update(span.source_text).digest('hex'));assert.equal(span.source_location.anchor_chunk_id,chunks[1].chunk_id);assert.equal(span.source_location.resolver_version,'evidence-source-span-v1');});

test('长 paragraph 的多 Chunk 重建为完整原段落且不跨段',()=>{const paragraph='甲'.repeat(50);const source=`${paragraph}\n\n下一段`;const{material,chunks}=fixture(source,{maxChars:12});const span=resolver.resolve({material,chunks,anchorChunkId:chunks[2].chunk_id,strategy:'paragraph_reconstruction'});assert.equal(span.source_text,paragraph);assert.equal(span.source_location.paragraph_start,1);assert.equal(span.source_location.paragraph_end,1);});

test('heading_group 包含真实标题及同组正文并在下一同级标题停止',()=>{const source='# 系统集成\n\n支持接口集成。\n\n支持系统对接。\n\n# 资质\n\nISO9001';const{material,chunks}=fixture(source);const span=resolver.resolve({material,chunks,anchorChunkId:chunks[1].chunk_id,strategy:'heading_group'});assert.match(span.source_text,/^# 系统集成/);assert.match(span.source_text,/支持系统对接/);assert.doesNotMatch(span.source_text,/资质/);});

test('Anchor 本身为 heading 时 auto 读取其下受限正文',()=>{const source='# 资质认证\n\nISO9001\n\nISO27001';const{material,chunks}=fixture(source);const span=resolver.resolve({material,chunks,anchorChunkId:chunks[0].chunk_id});assert.equal(span.source_location.resolution_method,'heading_group');assert.match(span.source_text,/ISO9001/);assert.match(span.source_text,/ISO27001/);});

test('bounded fallback 保持连续、包含 Anchor 且不跨明确 heading',()=>{const source='甲\n\n乙\n\n丙\n\n# 新章\n\n丁';const{material,chunks}=fixture(source);const span=resolver.resolve({material,chunks,anchorChunkId:chunks[1].chunk_id,strategy:'bounded_paragraph_window'});assert.match(span.source_text,/甲[\s\S]*乙[\s\S]*丙/);assert.doesNotMatch(span.source_text,/新章/);});

test('跨 Material、跨 chunker version 和不包含 Anchor 均被阻断',()=>{const{material,chunks}=fixture('甲\n\n乙');assert.throws(()=>resolver.resolve({material,chunks:[{...chunks[0],material_id:'other'}],anchorChunkId:chunks[0].chunk_id}),/Retrieval Anchor/);const mixed=[chunks[0],{...chunks[1],chunker_version:'future'}];const span=resolver.resolve({material,chunks:mixed,anchorChunkId:chunks[0].chunk_id,strategy:'bounded_paragraph_window'});assert.equal(span.source_text,'甲');});

test('客户端不得伪造 span、source text、hash 或 range',async()=>{const{material,chunks}=fixture('可验证原文');const repository={getCompanyMaterial:async()=>material,getMaterialChunk:async()=>chunks[0],findInvalidConfirmedRequirementIds:async()=>[],createEvidenceRecord:async(value)=>value};const service=new EvidenceService({repository});await assert.rejects(()=>service.create(PROJECT,{material_id:MATERIAL,source_chunk_id:chunks[0].chunk_id,title:'x',content:'x',resolved_source_span:{source_text:'伪造'}}),(error)=>error.code==='EVIDENCE_SOURCE_LINEAGE_FORBIDDEN');await assert.rejects(()=>service.create(PROJECT,{material_id:MATERIAL,source_chunk_id:chunks[0].chunk_id,title:'x',content:'x',source_text:'伪造'}),(error)=>error.code==='EVIDENCE_SOURCE_LINEAGE_INVALID');});

test('同 Anchor 完全相同 Span 去重，不同合法 Span 可创建新 draft 且不继承审批',async()=>{const source='# 标题\n\n原文能力。';const{material,chunks}=fixture(source);let records=[];const repository={getRetrievalEvidenceSource:async()=>({status:'succeeded',material_id:MATERIAL,chunk_id:chunks[1].chunk_id,material_type:'project_case',original_name:'m',...chunks[1]}),getCompanyMaterial:async()=>material,listMaterialChunks:async()=>chunks,getMaterialChunk:async()=>chunks[1],findInvalidConfirmedRequirementIds:async()=>[],findEvidenceBySourceSpan:async(_p,_m,start,end,hash)=>records.find((item)=>item.start===start&&item.end===end&&item.source_hash===hash)||null,createEvidenceRecord:async(value)=>{const item={id:String(records.length+1),approval_status:'draft',start:value.sourceLocation.char_start,end:value.sourceLocation.char_end,source_hash:value.sourceHash,...value};records.push(item);return item;}};const service=new EvidenceService({repository});const full=await service.createFromRetrieval(PROJECT,'REQ-030',{retrieval_run_id:PROJECT,chunk_id:chunks[1].chunk_id});assert.equal(full.created,true);assert.equal(full.evidence.approval_status,'draft');assert.equal((await service.createFromRetrieval(PROJECT,'REQ-030',{retrieval_run_id:PROJECT,chunk_id:chunks[1].chunk_id})).created,false);const anchor=await service.createFromRetrieval(PROJECT,'REQ-030',{retrieval_run_id:PROJECT,chunk_id:chunks[1].chunk_id,resolution_strategy:'anchor_only'});assert.equal(anchor.created,true);assert.equal(records.length,2);assert.equal(anchor.evidence.approval_status,'draft');});

test('Source Span v1 稳定 identity、exact slice、连续范围与原文保真',()=>{const source='  原始空格与 **Markdown**。\r\n\r\n- 列表 A\r\n- 列表 B';const{material,chunks}=fixture(source);const first=resolver.resolve({material,chunks,anchorChunkId:chunks[1].chunk_id,strategy:'bounded_paragraph_window'});const second=resolver.resolve({material,chunks:[...chunks].reverse(),anchorChunkId:chunks[1].chunk_id,strategy:'bounded_paragraph_window'});assert.equal(first.span_id,second.span_id);assert.equal(first.start_offset,second.start_offset);assert.equal(first.end_offset,second.end_offset);assert.equal(first.source_text_hash,second.source_text_hash);assert.equal(source.slice(first.start_offset,first.end_offset),first.source_text);assert.ok(first.source_text.includes('**Markdown**'));assert.ok(first.source_text.includes('\r\n'));assert.ok(first.start_offset<=chunks[1].char_start&&first.end_offset>=chunks[1].char_end);});

test('完整普通 Anchor 不扩大，超长 heading group 确定性 fallback',()=>{const plain=fixture('完整独立段落。');const direct=resolver.resolve({material:plain.material,chunks:plain.chunks,anchorChunkId:plain.chunks[0].chunk_id});assert.equal(direct.resolver_strategy,'anchor_only');assert.equal(direct.source_text,'完整独立段落。');const source=`# 性能报告\n\n${'甲'.repeat(SOURCE_SPAN_MAX_CHARS+200)}\n\n# 下一节\n\n结束`;const long=fixture(source,{maxChars:1000});const span=resolver.resolve({material:long.material,chunks:long.chunks,anchorChunkId:long.chunks[2].chunk_id,strategy:'heading_group'});assert.equal(span.resolver_strategy,'bounded_paragraph_window');assert.equal(span.fallback_reason,'HEADING_GROUP_EXCEEDS_MAX_CHARS');assert.ok(span.source_text.length<=SOURCE_SPAN_MAX_CHARS);assert.ok(span.start_offset<=long.chunks[2].char_start&&span.end_offset>=long.chunks[2].char_end);});

test('missing Material、missing Anchor、invalid offset 与 source mismatch 使用固定错误码',()=>{const{material,chunks}=fixture('真实原文');assert.throws(()=>resolver.resolve({material:null,chunks,anchorChunkId:chunks[0].chunk_id}),(error)=>error.code==='MATERIAL_NOT_FOUND');assert.throws(()=>resolver.resolve({material,chunks,anchorChunkId:'missing'}),(error)=>error.code==='ANCHOR_CHUNK_NOT_FOUND');assert.throws(()=>resolver.resolve({material,chunks:[{...chunks[0],char_end:999}],anchorChunkId:chunks[0].chunk_id}),(error)=>error.code==='ANCHOR_SOURCE_RANGE_INVALID');assert.throws(()=>resolver.resolve({material,chunks:[{...chunks[0],source_text:'改写文本'}],anchorChunkId:chunks[0].chunk_id}),(error)=>error.code==='SOURCE_TEXT_MISMATCH');});

test('Source Span Service 只持久化 Span，不调用外部服务或创建下游对象',async()=>{const{material,chunks}=fixture('# 报告\n\n测试对象：数据交换服务。\n指标：平均响应时间。\n结果：1.4 秒。');const calls={span:0,evidence:0,fact:0,mapping:0,claim:0,external:0};const repository={getCompanyMaterial:async()=>material,listMaterialChunks:async()=>chunks,getRetrievalEvidenceSource:async()=>({status:'succeeded',material_id:MATERIAL}),upsertEvidenceSourceSpan:async(span)=>{calls.span+=1;return span;}};const service=new EvidenceSourceSpanService({repository});const span=await service.resolveFromRetrieval({projectId:PROJECT,requirementId:'E2E-REQ-001',retrievalRunId:PROJECT,anchorChunkId:chunks[1].chunk_id});assert.equal(span.resolver_version,'evidence-source-span-v1');assert.match(span.source_text,/测试对象/);assert.match(span.source_text,/平均响应时间/);assert.match(span.source_text,/1\.4 秒/);assert.deepEqual(calls,{span:1,evidence:0,fact:0,mapping:0,claim:0,external:0});});

test('Markdown heading、bullet 与 table-like 原文只扩范围不改写',()=>{const source='# 参数组\n\n- 环境：测试环境\n- 日期：2026-01-01\n\n| 指标 | 数值 |\n| --- | --- |\n| P95 | 1.9 秒 |\n\n# 后续';const{material,chunks}=fixture(source);const span=resolver.resolve({material,chunks,anchorChunkId:chunks[2].chunk_id,strategy:'heading_group'});assert.equal(span.source_text,source.slice(span.start_offset,span.end_offset));assert.match(span.source_text,/^- 环境/m);assert.match(span.source_text,/\| P95 \| 1\.9 秒 \|/);assert.doesNotMatch(span.source_text,/# 后续/);});
