import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {buildSafePositiveWriterFixture} from '../src/pipeline/external-writer-preflight-v1.js';
import {OpenAICompatibleExternalWriterProvider,WriterExecutionService} from '../src/writer-execution-service.js';
import {assertSingleRegenerationScope,assertWriterStageFinalized,executeAuditedExternalWriter} from '../src/external-writer-execution-lifecycle.js';

const PROJECT='00000000-0000-4000-8000-000000000001';
function responseFor(fixture,override){return JSON.stringify(override??{choices:[{finish_reason:'stop',message:{content:JSON.stringify({blocks:[{block_id:'b1',text:fixture.claim.text,used_context_refs:[fixture.project_fact.project_fact_id],used_claim_refs:[fixture.claim.claim_id]}]})}}],usage:{prompt_tokens:8,completion_tokens:4}});}
async function localProviderServer(fixture){
  const server=http.createServer(async(req,res)=>{const mode=req.url.split('/')[1];for await(const _ of req){}if(mode==='reset'){req.socket.destroy();return;}const delays={delayed:3000,near:220,timeout:300};if(delays[mode])await new Promise(resolve=>setTimeout(resolve,delays[mode]));if(mode==='http500'){res.writeHead(500,{'content-type':'application/json'});res.end(JSON.stringify({error:{message:'fixture failure'}}));return;}res.writeHead(200,{'content-type':'application/json','x-request-id':`local-${mode}`});if(mode==='provider-invalid-json'){res.end('{');return;}if(mode==='invalid-json'){res.end(responseFor(fixture,{choices:[{finish_reason:'stop',message:{content:'{"blocks":['}}]}));return;}if(mode==='schema-invalid'){res.end(responseFor(fixture,{choices:[{finish_reason:'stop',message:{content:'{"blocks":[{"text":1}]}'}}]}));return;}res.end(responseFor(fixture));});
  server.listen(0,'127.0.0.1');await once(server,'listening');return server;
}
function repositoryFixture(){const states=[];return{states,async createExternalWriterCallAudit(){states.push('created');return{id:'audit-local'};},async transitionExternalWriterCallAudit(_id,state){states.push(state);},async finishExternalWriterCallAudit(_id,value){states.push(value.status);return value;}};}
async function run(base,fixture,timeoutMs=1000){const repository=repositoryFixture(),provider=new OpenAICompatibleExternalWriterProvider({apiBase:base,apiKey:'local-only',model:'local-fixture',timeoutMs,authorized:true}),started=Date.now();try{const value=await executeAuditedExternalWriter({task:fixture.writer_task,provider,service:new WriterExecutionService(),repository,auditInput:{},validationOptions:{writerModel:'local-fixture',promptVersion:'writer-prompt-v1',outputVersion:1}});return{...value,states:repository.states,elapsed:Date.now()-started};}catch(error){error.states=repository.states;error.elapsed=Date.now()-started;throw error;}}

test('正式 Adapter 即时和延迟 3 秒响应均等待至 completed',async()=>{const fixture=buildSafePositiveWriterFixture({projectId:PROJECT}),server=await localProviderServer(fixture),port=server.address().port;try{for(const mode of['immediate','delayed']){const result=await run(`http://127.0.0.1:${port}/${mode}/v1`,fixture,5000);assert.deepEqual(result.states,['created','dispatched','response_received','completed']);assert.equal(result.result.provider_audit.http_status,200);if(mode==='delayed')assert.ok(result.elapsed>=2900);}}finally{server.close();await once(server,'close');}});
test('接近 timeout 但在界内完成，超过 timeout 明确失败',async()=>{const fixture=buildSafePositiveWriterFixture({projectId:PROJECT}),server=await localProviderServer(fixture),port=server.address().port;try{const near=await run(`http://127.0.0.1:${port}/near/v1`,fixture,500);assert.equal(near.states.at(-1),'completed');await assert.rejects(()=>run(`http://127.0.0.1:${port}/timeout/v1`,fixture,80),error=>error.code==='EXTERNAL_WRITER_TIMEOUT'&&error.states.join(',')==='created,dispatched,failed'&&!error.states.includes('response_received'));}finally{server.close();await once(server,'close');}});
test('HTTP、连接、JSON 与 schema 失败都有确定分类和 failed 审计',async()=>{const fixture=buildSafePositiveWriterFixture({projectId:PROJECT}),server=await localProviderServer(fixture),port=server.address().port;try{const cases=[['http500','EXTERNAL_WRITER_PROVIDER_ERROR'],['reset','EXTERNAL_WRITER_NETWORK_ERROR'],['provider-invalid-json','EXTERNAL_WRITER_PROVIDER_INVALID_JSON'],['invalid-json','EXTERNAL_WRITER_INVALID_JSON'],['schema-invalid','EXTERNAL_WRITER_SCHEMA_INVALID']];for(const[mode,code]of cases)await assert.rejects(()=>run(`http://127.0.0.1:${port}/${mode}/v1`,fixture),error=>error.code===code&&error.states[0]==='created'&&error.states.at(-1)==='failed'&&error.code!=='EXTERNAL_WRITER_PROCESS_INTERRUPTED');}finally{server.close();await once(server,'close');}});
test('传播请求只在 finalized 首次输出与唯一完整 affected task 后开放',()=>{const pass={output:{status:'finalized'},guard:{status:'pass'},verification:{coverage_status:'complete'}};assert.equal(assertWriterStageFinalized(pass),true);for(const bad of[{...pass,output:{status:'rejected'}},{...pass,guard:{status:'failed'}},{...pass,verification:{coverage_status:'blocked'}}])assert.throws(()=>assertWriterStageFinalized(bad,'WRITER_FIRST_PASS_NOT_FINALIZED'),error=>error.code==='WRITER_FIRST_PASS_NOT_FINALIZED');assert.equal(assertSingleRegenerationScope({coverage_status:'complete',unresolved_targets:[],affected_writer_tasks:['WT-1']}),true);for(const plan of[{coverage_status:'partial',unresolved_targets:[],affected_writer_tasks:['WT-1']},{coverage_status:'complete',unresolved_targets:['chapter-x'],affected_writer_tasks:['WT-1']},{coverage_status:'complete',unresolved_targets:[],affected_writer_tasks:['WT-1','WT-2']}])assert.throws(()=>assertSingleRegenerationScope(plan),error=>error.code==='WRITER_REGENERATION_SCOPE_INVALID');});
