import test from 'node:test';import assert from 'node:assert/strict';import {checkLiveGateway,smokeLiveGateway,LIVE_TASKS} from '../src/pipeline/live-gateway-tools.js';
import {createProductionTaskProvider} from '../src/pipeline/production-task-provider.js';import {createWriterProvider} from '../src/pipeline/writer-provider.js';
const tasks=Object.keys(LIVE_TASKS);const secret='live-secret-must-not-leak';
function env(task,extra={}){const spec=LIVE_TASKS[task];const timeoutKey={response_planning:'V43_PLAN_TIMEOUT_MS',claim_generation:'V43_CLAIM_TIMEOUT_MS',section_drafting:'V43_WRITER_TIMEOUT_MS',targeted_revision:'V43_REVISION_TIMEOUT_MS'}[task];return{[`${spec.prefix}_API_BASE`]:'https://gateway.example/v1',[`${spec.prefix}_API_KEY`]:secret,[timeoutKey]:'30',V43_GATEWAY_USER:'test',...extra};}
function envelope(task){const data=task==='response_planning'?{response_plans:[]}:task==='claim_generation'?{claims:[]}:task==='section_drafting'?{chapter_id:'chapter-06',content_markdown:'安全响应。'}:{revised_text:'提供审计日志能力。'};return{schema_version:LIVE_TASKS[task].schema,task_type:task,status:'success',data,warnings:[]};}
function responsePayload(task,transform=(x)=>x){return new Response(JSON.stringify({data:{outputs:{response_payload_json:transform(JSON.stringify(envelope(task)))}}}),{status:200,headers:{'Content-Type':'application/json'}});}
test('四个 check 只调用 GET /info 且 Key 仅输出指纹',async()=>{for(const task of tasks){const calls=[];const result=await checkLiveGateway(task,{env:env(task),fetchImpl:async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify({name:`${task} app`,mode:'workflow'}),{status:200});}});assert.equal(calls.length,1);assert.ok(calls[0].url.endsWith('/info'));assert.equal(calls[0].options.method,'GET');assert.equal(result.workflow_called,false);assert.ok(!JSON.stringify(result).includes(secret));}});
test('四类 Provider 使用独立配置且不回退 DIFY',()=>{const e={GENERATION_PROVIDER:'semantic_gateway',V43_GATEWAY_USER:'u',DIFY_API_KEY:'wrong',V43_PLAN_GATEWAY_API_BASE:'https://plan',V43_PLAN_GATEWAY_API_KEY:'p',V43_CLAIM_GATEWAY_API_BASE:'https://claim',V43_CLAIM_GATEWAY_API_KEY:'c',V43_WRITER_GATEWAY_API_BASE:'https://writer',V43_WRITER_GATEWAY_API_KEY:'w',V43_REVISION_GATEWAY_API_BASE:'https://revision',V43_REVISION_GATEWAY_API_KEY:'r',V43_PLAN_TIMEOUT_MS:'101',V43_CLAIM_TIMEOUT_MS:'102',V43_WRITER_TIMEOUT_MS:'103',V43_REVISION_TIMEOUT_MS:'104'};const p=createProductionTaskProvider({env:e});const w=createWriterProvider({env:e});assert.equal(p.planClient.apiBase,'https://plan');assert.equal(p.planClient.timeoutMs,101);assert.equal(p.claimClient.timeoutMs,102);assert.equal(w.writerClient.timeoutMs,103);assert.equal(w.revisionClient.timeoutMs,104);assert.notEqual(p.planClient.apiKey,e.DIFY_API_KEY);});
test('四个 smoke 最多请求一次并输出冻结摘要',async()=>{for(const task of tasks){let calls=0;const result=await smokeLiveGateway(task,{env:env(task,{ALLOW_LIVE_MODEL_SMOKE:'true'}),fetchImpl:async()=>{calls++;return responsePayload(task);}});assert.equal(calls,1);assert.equal(result.workflow_calls,1);assert.equal(result.schema_version,LIVE_TASKS[task].schema);assert.ok(!JSON.stringify(result).includes(secret));}});
test('未授权 smoke 在网络请求前阻断',async()=>{let calls=0;await assert.rejects(()=>smokeLiveGateway('response_planning',{env:env('response_planning'),fetchImpl:async()=>{calls++;}}),(e)=>e.code==='LIVE_MODEL_SMOKE_NOT_ALLOWED');assert.equal(calls,0);});
test('禁止 result/text/answer 回退且缺少 response_payload_json 失败',async()=>{for(const field of ['result','text','answer'])await assert.rejects(()=>smokeLiveGateway('response_planning',{env:env('response_planning',{ALLOW_LIVE_MODEL_SMOKE:'true'}),fetchImpl:async()=>new Response(JSON.stringify({data:{outputs:{[field]:JSON.stringify(envelope('response_planning'))}}}),{status:200})}),(e)=>e.code==='GATEWAY_RESPONSE_PAYLOAD_MISSING');});
test('schema 不一致失败',async()=>{await assert.rejects(()=>smokeLiveGateway('claim_generation',{env:env('claim_generation',{ALLOW_LIVE_MODEL_SMOKE:'true'}),fetchImpl:async()=>responsePayload('claim_generation',(raw)=>raw.replace('4.3-claim-generation','4.3-wrong'))}),(e)=>e.code==='GATEWAY_ENVELOPE_INVALID');});
test('think 与单层 JSON 围栏确定性清理',async()=>{for(const wrap of [(x)=>`<think>ignore</think>\n${x}`,(x)=>`\`\`\`json\n${x}\n\`\`\``]){const result=await smokeLiveGateway('section_drafting',{env:env('section_drafting',{ALLOW_LIVE_MODEL_SMOKE:'true'}),fetchImpl:async()=>responsePayload('section_drafting',wrap)});assert.equal(result.status,'success');}});
test('截断 JSON、timeout 与 network 使用不同固定错误码',async()=>{await assert.rejects(()=>smokeLiveGateway('targeted_revision',{env:env('targeted_revision',{ALLOW_LIVE_MODEL_SMOKE:'true'}),fetchImpl:async()=>responsePayload('targeted_revision',(x)=>x.slice(0,-2))}),(e)=>e.code==='GATEWAY_TRUNCATED_JSON');await assert.rejects(()=>smokeLiveGateway('response_planning',{env:env('response_planning',{ALLOW_LIVE_MODEL_SMOKE:'true'}),fetchImpl:async(_u,{signal})=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('abort'),{name:'AbortError'}))))}),(e)=>e.code==='GATEWAY_TIMEOUT');await assert.rejects(()=>smokeLiveGateway('response_planning',{env:env('response_planning',{ALLOW_LIVE_MODEL_SMOKE:'true'}),fetchImpl:async()=>{throw new Error('offline');}}),(e)=>e.code==='GATEWAY_NETWORK_ERROR');});
