import test from 'node:test';
import assert from 'node:assert/strict';
import { MaterialProcessingCenterService } from '../src/material-processing-center-service.js';

const material={id:'MAT-1',original_name:'企业资质证明.pdf',material_type:'qualification',extraction_status:'succeeded',created_at:'2026-01-01'};
const readiness=(status='NO_EVIDENCE')=>({summary:{total_requirements:1,supported:status==='SUPPORTED'?1:0,readiness_rate:status==='SUPPORTED'?1:0},generation_readiness:{status:status==='SUPPORTED'?'READY_TO_GENERATE':'NEEDS_ATTENTION'},gaps:status==='SUPPORTED'?[]:[{requirement_id:'REQ-1'}],requirements:[{requirement_id:'REQ-1',readiness:status,is_mandatory:true}]});
function repository(overrides={}){return{listCompanyMaterials:async()=>[material],listMaterialProcessingActivity:async()=>[{material_id:'MAT-1',chunk_count:2,retrieval_run_count:1,retrieval_statuses:['succeeded']}],listEvidenceCandidateReviews:async()=>[],listEvidenceSourceFacts:async()=>[],listRequirementEvidenceFactMappings:async()=>[],...overrides};}

test('处理中心只聚合正式对象并用业务阶段表达待办',async()=>{const reviews=[{review_id:'RV-1',material_id:'MAT-1',requirement_ref:'REQ-1',review_status:'needs_review'}],service=new MaterialProcessingCenterService({repository:repository({listEvidenceCandidateReviews:async()=>reviews}),evidenceReadinessService:{get:async()=>readiness('NEEDS_REVIEW')}}),out=await service.get('P');assert.equal(out.materials[0].stage.code,'EVIDENCE_REVIEW');assert.equal(out.materials[0].stage.label,'证据待确认');assert.equal(out.materials[0].chunk_count,2);assert.equal(out.materials[0].affected_requirement_count,1);assert.equal(out.summary.pending_review,1);});

test('正式 Mapping 才能完成材料处理并投影缺口变化',async()=>{const reviews=[{review_id:'RV-1',material_id:'MAT-1',requirement_ref:'REQ-1',review_status:'approved'}],facts=[{fact_id:'F-1',material_id:'MAT-1',evidence_review_id:'RV-1',review_status:'approved'}],mappings=[{mapping_id:'M-1',material_id:'MAT-1',requirement_identifier:'REQ-1',evidence_fact_id:'F-1',review_status:'approved',fact_review_status:'approved',evidence_review_status:'approved',fact_current:true,mapping_current:true,support_level:'full_support',semantic_relationship:'direct'}],service=new MaterialProcessingCenterService({repository:repository({listEvidenceCandidateReviews:async()=>reviews,listEvidenceSourceFacts:async()=>facts,listRequirementEvidenceFactMappings:async()=>mappings}),evidenceReadinessService:{get:async()=>readiness('SUPPORTED')}}),out=await service.get('P');assert.equal(out.materials[0].stage.code,'COMPLETED');assert.deepEqual(out.materials[0].readiness_impact,[{requirement_id:'REQ-1',before:'NO_EVIDENCE',after:'SUPPORTED',mandatory:true}]);assert.equal(out.materials[0].resolved_gap_count,1);assert.equal(out.summary.remaining_gap_count,0);});

test('拒绝、冲突和解析失败不会伪装为处理完成',async()=>{const failedService=new MaterialProcessingCenterService({repository:repository({listCompanyMaterials:async()=>[{...material,extraction_status:'failed',extraction_error_code:'MATERIAL_EXTRACTION_FAILED'}]}),evidenceReadinessService:{get:async()=>readiness()}});assert.equal((await failedService.get('P')).materials[0].stage.action,'重新上传');const mappings=[{mapping_id:'M-1',material_id:'MAT-1',requirement_identifier:'REQ-1',review_status:'approved',support_level:'conflict',semantic_relationship:'conflict',fact_review_status:'approved',evidence_review_status:'approved',fact_current:true,mapping_current:true}],conflictService=new MaterialProcessingCenterService({repository:repository({listRequirementEvidenceFactMappings:async()=>mappings}),evidenceReadinessService:{get:async()=>readiness('CONFLICT')}});assert.equal((await conflictService.get('P')).materials[0].stage.code,'CONFLICT');});

test('读模型不会调用上传、审批、外部 Provider 或 Writer',async()=>{const calls={write:0,external:0},repo=repository({createCompanyMaterial:async()=>calls.write++,decideEvidenceCandidateReview:async()=>calls.write++}),service=new MaterialProcessingCenterService({repository:repo,evidenceReadinessService:{get:async()=>readiness()}});await service.get('P');assert.deepEqual(calls,{write:0,external:0});});
