import test from 'node:test';
import assert from 'node:assert/strict';
import {MAX_RERANK_SHIFT,rerankProductionCandidates} from '../src/pipeline/semantic-retrieval-reranker.js';

const raw=()=>Array.from({length:20},(_,index)=>({chunk_id:`E2E-C-${String(index+1).padStart(2,'0')}`,material_id:`E2E-M-${String(index+1).padStart(2,'0')}`,embedding_id:`E2E-E-${index+1}`,similarity_score:1-index/100,rank:index+1}));
const metadata=(need='project_experience',role='project_case')=>({requirement_role:{value:'atomic_requirement',status:'approved'},evidence_needs:[{value:need,status:'approved'}],candidate_roles:Object.fromEntries(raw().map((item)=>[item.chunk_id,{value:role,status:'approved'}]))});

test('failure injection: wrong Content Role never removes Broad Candidate and respects rank safety',()=>{const input=raw(),semantic=metadata();semantic.candidate_roles['E2E-C-01']={value:'company_positioning',status:'approved'};const result=rerankProductionCandidates(input,semantic);assert.equal(result.reranked_candidates.length,input.length);for(const item of result.reranked_candidates)assert.ok(Math.abs(item.reranked_rank-item.raw_vector_rank)<=MAX_RERANK_SHIFT);assert.ok(result.reranked_candidates.some((item)=>item.chunk_id==='E2E-C-01'));});
test('failure injection: wrong Evidence Need cannot hard exclude any Candidate',()=>{const input=raw(),result=rerankProductionCandidates(input,metadata('qualification','performance_test'));assert.deepEqual(new Set(result.reranked_candidates.map((item)=>item.chunk_id)),new Set(input.map((item)=>item.chunk_id)));});
test('failure injection: unknown Role or Need gives exact Raw order',()=>{for(const semantic of [metadata('unknown'),{...metadata(),requirement_role:{value:'unknown',status:'approved'}}]){const result=rerankProductionCandidates(raw(),semantic);assert.equal(result.fallback_mode,'raw_vector');assert.deepEqual(result.final_candidates.map((item)=>item.chunk_id),raw().slice(0,8).map((item)=>item.chunk_id));}});
test('failure injection: missing or pending semantic metadata gives strict Raw fallback',()=>{for(const semantic of [{},{...metadata(),requirement_role:{value:'atomic_requirement',status:'pending'}},{...metadata(),evidence_needs:[{value:'project_experience',status:'pending'}]}]){const result=rerankProductionCandidates(raw(),semantic);assert.equal(result.fallback_mode,'raw_vector');assert.deepEqual(result.reranked_candidates.map((item)=>item.chunk_id),raw().map((item)=>item.chunk_id));}});
