import test from 'node:test';
import assert from 'node:assert/strict';
import {MAX_RERANK_SHIFT,PRODUCTION_CANDIDATE_K,PRODUCTION_REVIEW_K,rerankProductionCandidates} from '../src/pipeline/semantic-retrieval-reranker.js';

const raw=()=>Array.from({length:20},(_,index)=>({chunk_id:`C-${String(index+1).padStart(2,'0')}`,material_id:`M-${String(index+1).padStart(2,'0')}`,embedding_id:`E-${index+1}`,similarity_score:1-index/100,rank:index+1,material_type:'product_documentation'}));
const semantic=()=>({requirement_role:{value:'atomic_requirement',status:'approved'},evidence_needs:[{value:'project_experience',status:'approved'}],candidate_roles:Object.fromEntries(raw().map((item,index)=>[item.chunk_id,{value:index===5?'project_case':'technical_reference',status:'approved'}]))});

test('Production v1 freezes broad 20, final 8 and bounded adjustment',()=>{assert.equal(PRODUCTION_CANDIDATE_K,20);assert.equal(PRODUCTION_REVIEW_K,8);assert.equal(MAX_RERANK_SHIFT,4);});
test('missing, empty, pending or unknown semantics preserve Raw Vector order',()=>{for(const metadata of [{},{requirement_role:{value:'unknown',status:'approved'},evidence_needs:[{value:'project_experience',status:'approved'}]},{requirement_role:{value:'atomic_requirement',status:'approved'},evidence_needs:[]},{requirement_role:{value:'atomic_requirement',status:'pending'},evidence_needs:[{value:'project_experience',status:'approved'}]}]){const result=rerankProductionCandidates(raw(),metadata);assert.equal(result.fallback_mode,'raw_vector');assert.deepEqual(result.reranked_candidates.map((x)=>x.chunk_id),raw().map((x)=>x.chunk_id));}});
test('unknown and incompatible candidates remain in Broad audit',()=>{const metadata=semantic();metadata.candidate_roles['C-01']={value:'unknown',status:'approved'};let result=rerankProductionCandidates(raw(),metadata);assert.equal(result.fallback_mode,'raw_vector');metadata.candidate_roles['C-01']={value:'company_positioning',status:'approved'};result=rerankProductionCandidates(raw(),metadata);assert.equal(result.reranked_candidates.length,20);assert.ok(result.reranked_candidates.some((x)=>x.chunk_id==='C-01'&&x.role_compatibility==='incompatible'));});
test('deterministic rerank has stable tie-break and complete audit',()=>{const candidates=raw();candidates[0].rank=1;candidates[1].rank=1;candidates[0].similarity_score=candidates[1].similarity_score;const first=rerankProductionCandidates(candidates,semantic()),second=rerankProductionCandidates([...candidates].reverse(),semantic());assert.deepEqual(first.reranked_candidates.map((x)=>x.chunk_id),second.reranked_candidates.map((x)=>x.chunk_id));assert.equal(first.final_candidates.length,8);for(const item of first.reranked_candidates)for(const field of ['source_document_id','source_chunk_id','raw_vector_rank','raw_similarity','reranked_rank','content_role','role_compatibility','matched_evidence_needs','rerank_reasons','retrieval_contract_version','rerank_version'])assert.ok(Object.hasOwn(item,field),field);});
test('reranker is pure and cannot create Evidence, Facts, Mappings or Claims',()=>{const result=rerankProductionCandidates(raw(),semantic());assert.deepEqual(Object.keys(result).sort(),['fallback_mode','final_candidates','raw_candidates','reranked_candidates']);assert.equal(JSON.stringify(result).includes('approved Evidence'),false);});
