import test from 'node:test';import assert from 'node:assert/strict';
import { buildCompatibilityMatrix, compatibilityFor, createRequirementCandidate, NEED_TYPES } from '../eval/semantic-boundary/contract.js';
import { runCoverageAudit } from '../eval/semantic-boundary/audit-runner.js';
import { buildEvaluationSnapshot, validateEvaluationSnapshot } from '../eval/semantic-boundary/snapshot.js';

test('Candidate Contract 保留 response/evidence 分离、unknown 与多 Evidence Need',()=>{const context=createRequirementCandidate({requirement_id:'R1',requirement_text:'总体目标',requirement_role:'context_goal',response_required:true,evidence_required:false,evidence_needs:[],review_status:'pending'});assert.equal(context.response_required,true);assert.equal(context.evidence_required,false);const multi=createRequirementCandidate({requirement_id:'R2',requirement_text:'通用复合要求',requirement_role:'composite_requirement',response_required:true,evidence_required:true,evidence_needs:[{type:'qualification',review_status:'pending'},{type:'implementation',review_status:'pending'}],review_status:'pending'});assert.equal(multi.evidence_needs.length,2);assert.doesNotThrow(()=>createRequirementCandidate({requirement_id:'R3',requirement_text:'不确定',requirement_role:'unknown',evidence_needs:[{type:'unknown',review_status:'pending'}]}));});
test('Compatibility Matrix domain-neutral 且 authority 不替代 sufficiency',()=>{assert.equal(compatibilityFor('quantitative_performance','performance_test'),'preferred');assert.equal(compatibilityFor('quantitative_performance','company_positioning'),'incompatible');assert.equal(compatibilityFor('project_experience','project_case'),'preferred');const json=JSON.stringify(buildCompatibilityMatrix());for(const token of ['smart_city','medical','智慧城市','医疗'])assert.equal(json.includes(token),false);assert.equal(buildCompatibilityMatrix().length,NEED_TYPES.length);});
test('Coverage Audit 对缺失 221/81 inventory 显式降级且所有 Candidate 保持 pending',()=>{const report=runCoverageAudit();assert.equal(report.inventory.expected.requirements,221);assert.equal(report.inventory.full_live_inventory_available,false);assert.equal(report.requirements.length,10);assert.ok(report.requirements.every((x)=>x.review_status==='pending'));assert.ok(report.contents.every((x)=>x.review_status==='pending'));assert.equal(report.requirements.find((x)=>x.requirement_id==='REQ-001').response_required,true);assert.equal(report.requirements.find((x)=>x.requirement_id==='REQ-001').evidence_required,false);assert.ok(report.failures.some((x)=>x.type==='ROLE_MISMATCH'));const cloud=report.failures.find((x)=>x.requirement_id==='REQ-047');assert.equal(cloud.source_authority,'government_primary');assert.equal(cloud.evidence_sufficiency,'none');assert.equal(report.failures.some((x)=>x.type==='RETRIEVAL_MISS'),false);});
test('Frozen Snapshot 验证 count、lineage、range、hash 且明确不完整 benchmark',()=>{const snapshot=buildEvaluationSnapshot();const result=validateEvaluationSnapshot(snapshot);assert.equal(result.ok,true,result.errors.join(','));assert.equal(result.benchmark_complete,false);assert.deepEqual(snapshot.metadata.declared_counts,{requirements:10,materials:4,chunks:81});const broken=structuredClone(snapshot);broken.chunks[0].chunk_hash='0'.repeat(64);assert.equal(validateEvaluationSnapshot(broken).ok,false);});
test('同一 Frozen Snapshot 连续 Audit 完全一致',()=>{const snapshot=buildEvaluationSnapshot();assert.deepEqual(runCoverageAudit(snapshot),runCoverageAudit(snapshot));});
