ALTER TABLE document_versions ALTER COLUMN generation_id DROP NOT NULL;
ALTER TABLE document_versions DROP CONSTRAINT IF EXISTS document_versions_generation_id_key;
ALTER TABLE document_versions ADD COLUMN IF NOT EXISTS parent_version_id uuid REFERENCES document_versions(id) ON DELETE SET NULL, ADD COLUMN IF NOT EXISTS regenerated_chapter_id text, ADD COLUMN IF NOT EXISTS draft_text text, ADD COLUMN IF NOT EXISTS sanitized_text text, ADD COLUMN IF NOT EXISTS revised_text text, ADD COLUMN IF NOT EXISTS final_text text, ADD COLUMN IF NOT EXISTS validation_errors jsonb NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS removed_items jsonb NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS coverage_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb, ADD COLUMN IF NOT EXISTS requirement_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS claim_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS evidence_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS chapter_tasks jsonb NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS provider_audit jsonb NOT NULL DEFAULT '[]'::jsonb, ADD COLUMN IF NOT EXISTS rule_versions jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE document_versions DROP CONSTRAINT IF EXISTS document_versions_status_check;
ALTER TABLE document_versions ADD CONSTRAINT document_versions_status_check CHECK(status IN('pending_confirmation','pending_review','confirmed'));
CREATE TABLE IF NOT EXISTS document_generations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,status text NOT NULL CHECK(status IN('created','queued','running','succeeded','failed','merged','sanitized','validated','revision_required','revised','finalized')),risk_status text CHECK(risk_status IN('pass','warning','critical')),error_code text,error_message text,coverage_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,requirement_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,claim_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,evidence_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,provider_audit jsonb NOT NULL DEFAULT '[]'::jsonb,rule_versions jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS document_generation_tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),generation_id uuid NOT NULL REFERENCES document_generations(id) ON DELETE CASCADE,chapter_id text NOT NULL,batch_index integer NOT NULL,status text NOT NULL CHECK(status IN('created','queued','running','succeeded','failed','merged','sanitized','validated','revision_required','revised','finalized')),input_snapshot jsonb NOT NULL,output_markdown text,claim_ids jsonb NOT NULL DEFAULT '[]'::jsonb,attempt integer NOT NULL DEFAULT 0,runtime_ms integer,error_code text,error_message text,provider_audit jsonb NOT NULL DEFAULT '{}'::jsonb,claimed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(generation_id,chapter_id,batch_index));
CREATE INDEX IF NOT EXISTS document_generations_project_idx ON document_generations(project_id,created_at DESC);
CREATE INDEX IF NOT EXISTS document_generation_tasks_generation_idx ON document_generation_tasks(generation_id,chapter_id,batch_index);
