CREATE TABLE IF NOT EXISTS project_facts (
  project_fact_id text PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  fact_key text NOT NULL,
  fact_role text NOT NULL,
  value_type text NOT NULL,
  value_payload jsonb,
  unit text,
  value_status text NOT NULL,
  scope jsonb NOT NULL DEFAULT '[]'::jsonb,
  provenance_refs jsonb NOT NULL,
  source_hashes jsonb NOT NULL,
  payload_hash text NOT NULL,
  review_status text NOT NULL DEFAULT 'proposed',
  conflict_status text NOT NULL DEFAULT 'none',
  created_by_type text NOT NULL,
  created_by text NOT NULL,
  reviewed_by text,
  reviewed_at timestamptz,
  human_review_version integer NOT NULL DEFAULT 0,
  review_note text,
  contract_version text NOT NULL,
  candidate_version text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  supersedes_project_fact_id text REFERENCES project_facts(project_fact_id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_fact_id_format CHECK(project_fact_id ~ '^PFACT-[0-9A-F]{32}$'),
  CONSTRAINT project_fact_role CHECK(fact_role IN ('requirement_constraint','enterprise_fact','project_decision','response_commitment','assignment','unknown')),
  CONSTRAINT project_fact_value_type CHECK(value_type IN ('string','exact_decimal','date','duration','enum','string_set','structured')),
  CONSTRAINT project_fact_value_status CHECK(value_status IN ('known','pending')),
  CONSTRAINT project_fact_review_status CHECK(review_status IN ('proposed','needs_review','approved','rejected','invalidated')),
  CONSTRAINT project_fact_conflict_status CHECK(conflict_status IN ('none','conflict','resolved')),
  CONSTRAINT project_fact_created_by_type CHECK(created_by_type IN ('system','human')),
  CONSTRAINT project_fact_contract CHECK(contract_version='project-fact-control-v1'),
  CONSTRAINT project_fact_hash CHECK(payload_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT project_fact_pending_value CHECK((value_status='pending' AND value_payload IS NULL) OR (value_status='known' AND value_payload IS NOT NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS project_fact_identity_idx ON project_facts(project_id,fact_key,payload_hash,contract_version,candidate_version);
CREATE INDEX IF NOT EXISTS project_fact_review_idx ON project_facts(project_id,review_status,fact_key);
CREATE INDEX IF NOT EXISTS project_fact_conflict_idx ON project_facts(project_id,conflict_status,fact_key);
