import React,{useEffect,useState}from'react';
import{api}from'./api.js';
import{formatMaterialType}from'./material-types.js';

const SUPPORT_LEVELS=[
  {value:'full_support',label:'完整支撑',help:'该证据可直接支持当前 Requirement 所需的相关事实，但不代表可以跳过 Claim Gate。'},
  {value:'partial_support',label:'部分支撑',help:'只能证明部分事实或较弱范围。'},
  {value:'reference_only',label:'仅供参考',help:'主题相关，但不足以作为正式强事实支撑。'}
];
const split=(value)=>String(value||'').split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);
const location=(value={})=>{const parts=[];if(value.page_start)parts.push(`第 ${value.page_start}${value.page_end&&value.page_end!==value.page_start?`-${value.page_end}`:''} 页`);if(value.paragraph_start)parts.push(`第 ${value.paragraph_start}${value.paragraph_end&&value.paragraph_end!==value.paragraph_start?`-${value.paragraph_end}`:''} 段`);if(value.section)parts.push(value.section);return parts.join(' · ')||'原始材料分片';};

export function EvidenceReview({projectId,requirements=[],initialReview=null}){
  const [selected,setSelected]=useState(requirements[0]?.req_id||'');
  const [state,setState]=useState({loading:!initialReview,review:initialReview,error:''});
  const [activeChunk,setActiveChunk]=useState(initialReview?.results?.[0]?.chunk_id||'');
  const [candidate,setCandidate]=useState({title:'',evidence_scope:'',capability_tags:''});
  const [mapping,setMapping]=useState({support_level:'',review_notes:''});
  const [validity,setValidity]=useState('active');
  async function load(req=selected){if(!req)return;setState(s=>({...s,loading:true,error:''}));try{const review=await api.getRequirementEvidenceReview(projectId,req);setState({loading:false,review,error:''});setActiveChunk(review.results?.[0]?.chunk_id||'');}catch(error){setState({loading:false,review:null,error:error.message});}}
  useEffect(()=>{if(!initialReview&&selected)load(selected);},[projectId,selected]);
  const review=state.review;const result=review?.results?.find(x=>x.chunk_id===activeChunk)||review?.results?.[0];
  async function action(work){try{await work();await load();}catch(error){setState(s=>({...s,error:error.message}));}}
  const createCandidate=()=>result&&action(()=>api.createEvidenceCandidateFromRetrieval(projectId,review.requirement.req_id,{retrieval_run_id:review.retrieval_run.retrieval_run_id,chunk_id:result.chunk_id,title:candidate.title||`${result.material_name} 来源证据`,evidence_type:result.material_type,evidence_scope:split(candidate.evidence_scope),capability_tags:split(candidate.capability_tags)}));
  const decideEvidence=(decision)=>result?.evidence_id&&action(()=>api.decideEvidence(result.evidence_id,decision));
  const reviewValidity=()=>result?.evidence_id&&action(()=>api.reviewEvidenceValidity(result.evidence_id,validity));
  const propose=()=>result?.evidence_id&&action(()=>api.proposeEvidenceMapping(projectId,{requirement_id:review.requirement.req_id,evidence_id:result.evidence_id,mapping_source:'retrieval',support_level:mapping.support_level,review_notes:mapping.review_notes,retrieval_run_id:review.retrieval_run.retrieval_run_id,retrieval_chunk_id:result.chunk_id,created_by:'current_user'}));
  const decideMapping=(decision)=>result?.mapping_id&&action(()=>api.decideEvidenceMapping(result.mapping_id,decision));
  return <div className="evidence-review-layout">
    <section className="card review-requirements"><h2>企业证据复核</h2><p>按 Requirement 查看检索结果，分别审核 Evidence 与支撑关系。</p><label className="field"><span>Canonical Requirement</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">请选择</option>{requirements.map(r=><option key={r.req_id} value={r.req_id}>{r.req_id} · {r.content||r.text}</option>)}</select></label>{review?.requirement?<div className="requirement-summary"><strong>{review.requirement.req_id}</strong><p>{review.requirement.text}</p><div className="tag-row"><span>{review.requirement.category||'未分类'}</span><span>{review.requirement.is_mandatory?'实质性要求':'一般要求'}</span>{review.requirement.requires_confirmation?<span>需确认</span>:null}</div></div>:null}{state.error?<div className="notice error">{state.error}</div>:null}</section>
    <section className="card review-results"><div className="section-heading"><div><h2>Retrieval Top-K</h2><p>检索相关度仅表示语义接近，不代表证据可信度、需求满足度或支撑强度。</p></div></div>{state.loading?<p>正在加载复核数据…</p>:null}<div className="retrieval-list">{(review?.results||[]).map(item=><button type="button" className={`retrieval-result ${item.chunk_id===result?.chunk_id?'selected':''}`} key={item.chunk_id} onClick={()=>setActiveChunk(item.chunk_id)}><span className="rank">#{item.rank}</span><span><strong>{item.material_name}</strong><small>{formatMaterialType(item.material_type)} · 检索相关度 {(Number(item.similarity_score||0)*100).toFixed(1)}%</small></span>{item.material_type==='historical_bid'?<em>历史标书，仅供参考</em>:null}</button>)}</div>
    {result?<div className="review-detail"><h3>来源原文</h3><p className="source-preview">{result.source_text_preview||'无可用预览'}</p><small>{location(result.source_location)}</small>{result.material_type==='historical_bid'?<div className="notice warning">历史标书，仅供参考。不得直接升级为企业正式能力事实。</div>:null}
      {!result.evidence_id?<div className="review-form"><h3>创建 Evidence Candidate</h3><label className="field"><span>标题</span><input value={candidate.title} onChange={e=>setCandidate({...candidate,title:e.target.value})}/></label><label className="field"><span>Evidence scope（逗号分隔）</span><input value={candidate.evidence_scope} onChange={e=>setCandidate({...candidate,evidence_scope:e.target.value})}/></label><label className="field"><span>Capability tags（逗号分隔）</span><input value={candidate.capability_tags} onChange={e=>setCandidate({...candidate,capability_tags:e.target.value})}/></label><button className="primary-inline" onClick={createCandidate}>创建 Evidence Candidate</button></div>:
      <div className="review-form"><h3>Evidence Review</h3><div className="tag-row"><span>approval: {result.approval_status}</span><span>validity: {result.validity_status}</span><span>来源链：Material / Chunk 已绑定</span></div><p>Scope：{result.evidence_scope?.join('、')||'—'} · Tags：{result.capability_tags?.join('、')||'—'}</p><div className="compact-actions"><button onClick={()=>decideEvidence('approve')} disabled={result.approval_status==='approved'}>批准为企业证据</button><button onClick={()=>decideEvidence('reject')} disabled={result.approval_status==='rejected'}>拒绝 Evidence</button><select value={validity} onChange={e=>setValidity(e.target.value)}><option value="active">有效</option><option value="unknown">待复核</option><option value="expired">已过期</option><option value="revoked">已撤销</option></select><button onClick={reviewValidity}>保存有效性</button></div>
      {result.approval_status==='approved'?<div className="mapping-review"><h3>Requirement-Evidence Mapping</h3>{result.mapping_id?<><div className="tag-row"><span>{result.mapping_status}</span><span>{result.support_level||'未选择支撑级别'}</span></div><p>{result.review_notes||'无审核说明'}</p><div className="compact-actions"><button onClick={()=>decideMapping('approve')} disabled={result.mapping_status==='approved'}>批准 Mapping</button><button onClick={()=>decideMapping('reject')} disabled={result.mapping_status==='rejected'}>拒绝 Mapping</button></div></>:<><label className="field"><span>支撑级别</span><select value={mapping.support_level} onChange={e=>setMapping({...mapping,support_level:e.target.value})}><option value="">请人工选择</option>{SUPPORT_LEVELS.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>{SUPPORT_LEVELS.map(x=><p className="support-help" key={x.value}><strong>{x.label}：</strong>{x.help}</p>)}<label className="field"><span>Review notes</span><textarea value={mapping.review_notes} onChange={e=>setMapping({...mapping,review_notes:e.target.value})}/></label><button className="primary-inline" onClick={propose} disabled={!mapping.support_level}>创建 proposed Mapping</button></>}</div>:<p className="helper">批准为企业证据后，才能审核它对当前 Requirement 的支撑关系。</p>}</div>}</div>:<div className="empty-state"><strong>暂无 Retrieval Result</strong><p>请先为该 Requirement 执行企业材料检索。</p></div>}</section>
  </div>;
}

export{SUPPORT_LEVELS};
