import React,{useEffect,useState}from'react';
import{api}from'./api.js';
const LABEL={proposed:'待确认',needs_review:'需要复核',draft:'草稿待审',pending:'信息待补充',conflict:'事实冲突',insufficient:'材料不足',restrict:'限制使用',reject:'禁止使用',rejected:'已拒绝',approved:'已批准',unknown:'未知状态（需人工核验）',blocked:'传播受阻',unresolved:'尚未解决'};
const showValue=f=>typeof f.value==='object'?JSON.stringify(f.value,null,2):String(f.value??'');
export function ReviewWorkbench({projectId,focusMaterialId=null,onClearMaterialFocus,initialData=null}){
 const[state,setState]=useState({loading:!initialData,data:initialData,error:'',message:''}),[filter,setFilter]=useState('pending'),[edit,setEdit]=useState(null);
 async function load(){try{const data=await api.getReviewCenter(projectId);setState({loading:false,data,error:'',message:''});}catch(error){setState({loading:false,data:null,error:error.message,message:''});}}
 useEffect(()=>{if(!initialData)load();},[projectId]);
 async function act(work){try{await work();await load();}catch(error){setState(s=>({...s,error:error.message}));}}
 async function beginEdit(fact){try{setEdit({fact,impact:await api.getProjectFactImpact(projectId,fact.project_fact_id),newValue:showValue(fact),note:''});}catch(error){setState(s=>({...s,error:error.message}));}}
 async function saveEdit(){let next=edit.newValue;if(['structured','string_set'].includes(edit.fact.value_type)){try{next=JSON.parse(next);}catch{return setState(s=>({...s,error:'新值必须是合法 JSON。'}));}}const result=await api.editProjectFact(edit.fact.project_fact_id,{value:next,value_status:'known'},edit.note);setEdit(null);await load();setState(s=>({...s,message:`事实已生成新版本；${result.propagation.affected_target_count} 个目标和 ${result.propagation.mention_count} 条引用已进入传播失效控制。`}));}
 if(state.loading)return <section className="card">正在加载审核中心…</section>;
 if(!state.data)return <section className="card"><div className="notice error">{state.error}</div></section>;
 const d=state.data,allItems=filter==='all'?[...d.evidence,...(d.evidence_facts||[]),...d.mappings,...d.claims,...d.project_facts,...(d.propagation||[])]:d.pending,items=focusMaterialId?allItems.filter(item=>item.material_id===focusMaterialId):allItems;
 return <div className="review-workbench"><section className="card"><div className="section-heading"><div><h2>审核与控制中心</h2><p>集中处理需要您确认的证据、材料证明内容和需求匹配情况。</p>{focusMaterialId?<p>当前仅显示刚才所选材料的审核事项。<button onClick={onClearMaterialFocus}>查看全部待办</button></p>:null}</div><select className="workbench-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">只看待办</option><option value="all">全部控制项</option></select></div>
 <div className="parse-summary"><div><span>全部待办</span><strong>{d.summary.pending}</strong></div><div><span>证据确认</span><strong>{d.summary.evidence_confirmation}</strong></div><div><span>事实确认 / 冲突</span><strong>{d.summary.fact_confirmation} / {d.summary.fact_conflict}</strong></div><div><span>风险声明 / 缺材料</span><strong>{d.summary.risky_claims} / {d.summary.missing_materials}</strong></div></div>{state.error?<div className="notice error">{state.error}</div>:null}{state.message?<div className="notice success">{state.message}</div>:null}
 <div className="control-list">{items.length?items.map(item=><article className="control-item" key={`${item.kind}-${item.id||item.project_fact_id}`}><header><strong>{item.kind==='evidence_review'?`${item.requirement_id} · 证据确认`:item.kind==='evidence_fact'?`${item.requirement_id||'未关联需求'} · 材料证明内容确认`:item.kind==='mapping'?`${item.requirement_id} · 需求匹配确认`:item.kind==='claim'?`${item.requirement_id} · 风险声明`:item.kind==='propagation'?`${item.target_type} ${item.target_id} · 传播控制`:`${item.key} · 项目事实`}</strong><span className={`badge ${item.status}`}>{LABEL[item.status]||'未知状态（需人工核验）'}</span></header><p>{item.requirement_text||item.text||(item.kind==='evidence_fact'?'请核验从材料中提取的证明内容。技术编号可在高级信息中查看。':item.kind==='propagation'?`关联 Project Fact：${item.project_fact_id}`:showValue(item))}</p><small>{item.reason}</small>
 {item.kind==='evidence_review'?<><p>{item.is_mandatory?'★ 实质性要求':'一般要求'} · 来源：第 {item.source_location?.page_start||'—'} 页 / 第 {item.source_location?.paragraph_start||'—'} 段</p><details><summary>查看来源与高级信息</summary><p>招标要求：{item.requirement_text}</p><p>材料：{item.source_material||'—'}</p><pre>{item.source_excerpt}</pre><p>支撑程度：{item.support_level||'待确认'} · 有效性：{item.fact?.validity?.status||'待确认'}</p><p>确认原因：{item.reason}</p>{item.fact?<p>材料证明内容编号：{item.fact.fact_id} · {LABEL[item.fact.status]||item.fact.status}</p>:null}<p><code>来源片段：{item.source_span_id}</code></p></details><div className="compact-actions"><button onClick={()=>act(()=>api.decideEvidenceReview(item.id,'approve','人工核验来源与需求一致'))}>确认可作为证据</button><button onClick={()=>act(()=>api.decideEvidenceReview(item.id,'reject','人工判定不可作为证据'))}>确认不可作为证据</button>{item.fact?.status==='draft'?<><button onClick={()=>act(()=>api.decideEvidenceSourceFact(item.fact.fact_id,'approve','人工核验原子事实'))}>确认证明内容</button><button onClick={()=>act(()=>api.decideEvidenceSourceFact(item.fact.fact_id,'reject','事实不成立'))}>拒绝证明内容</button></>:null}</div></>:null}
 {item.kind==='evidence_fact'?<><details><summary>高级信息</summary><code>证明内容编号：{item.id} · 来源片段：{item.source_span_id}</code></details><div className="compact-actions"><button onClick={()=>act(()=>api.decideEvidenceSourceFact(item.id,'approve','人工核验原子事实'))}>确认证明内容</button><button onClick={()=>act(()=>api.decideEvidenceSourceFact(item.id,'reject','事实不成立'))}>拒绝证明内容</button></div></>:null}{item.kind==='mapping'?<><p>请确认这份材料证明内容能否支持对应招标要求。</p><div className="compact-actions"><button onClick={()=>act(()=>api.decideRequirementFactMapping(item.id,'approve','人工确认需求匹配关系'))}>确认匹配</button><button onClick={()=>act(()=>api.decideRequirementFactMapping(item.id,'reject','人工判定不能支持该需求'))}>确认不匹配</button></div></>:null}{item.kind==='project_fact'?<><p>角色：{item.fact_role} · 版本 V{item.version} · 影响章节 {item.affected_chapters?.length||0} · 目标 {item.affected_target_count} · 引用 {item.mention_count}</p><details><summary>查看 Provenance</summary><pre>{JSON.stringify(item.provenance_refs,null,2)}</pre></details><div className="compact-actions"><button disabled={item.conflict_status==='conflict'} onClick={()=>act(()=>api.decideProjectFact(item.project_fact_id,'approve','人工确认项目事实'))}>批准</button><button onClick={()=>act(()=>api.decideProjectFact(item.project_fact_id,'reject','人工拒绝项目事实'))}>拒绝</button><button onClick={()=>beginEdit(item)}>正式编辑</button></div></>:null}{item.reason_codes?.length?<details><summary>高级审计详情</summary><code>{item.reason_codes.join(' · ')}</code></details>:null}</article>):<p>当前筛选下没有控制项。</p>}</div></section>
 {edit?<section className="card fact-edit"><h2>Project Fact 正式编辑预览</h2><p><strong>当前值：</strong>{showValue(edit.fact)}</p><label className="field"><span>新值</span><textarea value={edit.newValue} onChange={e=>setEdit({...edit,newValue:e.target.value})}/></label><label className="field"><span>编辑原因 *</span><textarea value={edit.note} onChange={e=>setEdit({...edit,note:e.target.value})}/></label><div className="warning-summary"><strong>后端影响范围</strong><p>目标 {edit.impact.affected_target_count} · 章节 {edit.impact.affected_chapters.join('、')||'无'} · Writer Task {edit.impact.affected_writer_tasks.length} · Mention {edit.impact.mention_count} · 未解决 {edit.impact.unresolved_count}</p></div><div className="compact-actions"><button disabled={!edit.note.trim()} onClick={()=>act(saveEdit)}>提交正式 Human Edit</button><button onClick={()=>setEdit(null)}>取消</button></div></section>:null}</div>;
}
